### ISSUE TITLE
NullPointerException in Snackbar

### ISSUE THREAD

**Issue by ZieIony** [ZieIony/Carbon#105]
```
06-03 11:31:52.870    3930-3930/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: tk.zielony.carbonsamples, PID: 3930
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setTranslationY(float)' on a null object reference
            at com.nineoldandroids.view.ViewHelper$Honeycomb.setTranslationY(ViewHelper.java:273)
            at com.nineoldandroids.view.ViewHelper.setTranslationY(ViewHelper.java:151)
            at carbon.widget.Snackbar$4.onAnimationUpdate(Snackbar.java:191)
            at com.nineoldandroids.animation.ValueAnimator.animateValue(ValueAnimator.java:1178)
            at com.nineoldandroids.animation.ValueAnimator.animationFrame(ValueAnimator.java:1139)
            at com.nineoldandroids.animation.ValueAnimator$AnimationHandler.handleMessage(ValueAnimator.java:650)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by ZieIony** [comment]
Should be fine now

**Comment by ramanaptr** [comment]
```
final Snackbar snackbar = new Snackbar(LenderWithdrawReviewActivity.this, "Hello world!", getResources().getInteger(R.integer.carbon_snackbarDuration));
        snackbar.show(root);
```

```android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #29: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.view.View.inflate(View.java:24394)
        at carbon.widget.SnackbarView.initSnackbar(SnackbarView.java:28)
        at carbon.widget.SnackbarView.<init>(SnackbarView.java:17)
        at carbon.widget.Snackbar$SnackbarLayout.<init>(Snackbar.java:327)
        at carbon.widget.Snackbar.<init>(Snackbar.java:67)
```

i have problem with this, you can help me?

**Comment by ramanaptr** [comment]
```
final Snackbar snackbar = new Snackbar(MainActivity.this, "Hello world!", getResources().getInteger(R.integer.carbon_snackbarDuration));
        snackbar.show(root);
```

```android.view.InflateException: Binary XML file line #29: Binary XML file line #29: Error inflating class <unknown>
    Caused by: android.view.InflateException: Binary XML file line #29: Error inflating class <unknown>
    Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.view.View.inflate(View.java:24394)
        at carbon.widget.SnackbarView.initSnackbar(SnackbarView.java:28)
        at carbon.widget.SnackbarView.<init>(SnackbarView.java:17)
        at carbon.widget.Snackbar$SnackbarLayout.<init>(Snackbar.java:327)
        at carbon.widget.Snackbar.<init>(Snackbar.java:67)
```

i have problem with this, you can help me?

**Comment by ZieIony** [comment]
Please don't post unrelated issues as comments to other, closed issues. It makes finding and tracking things more difficult.

I created a new issue to track your case: #398
