### ISSUE TITLE
recyclerview with mapfragment header

### ISSUE THREAD

**Issue by FunnyDevs** [ZieIony/Carbon#113]
Hi! If i try to insert a mapfragment on header layout file occurs an error. Is possibile to insert a mapfragment o i have to do a workaround?

**Comment by ZieIony** [comment]
Can you please post your error message here?

RecyclerView should be able to use any View (not Fragment) as a header. Google Maps have specific needs, maybe there's a problem with OpenGL or threading?

**Comment by FunnyDevs** [comment]
This is the stacktrace

FATAL EXCEPTION: main
    java.lang.NullPointerException
            at android.view.SurfaceView.updateWindow(SurfaceView.java:476)
            at android.view.SurfaceView.dispatchDraw(SurfaceView.java:348)
            at com.google.maps.api.android.lib6.gmm6.n.bw.dispatchDraw(Unknown Source)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.View.draw(View.java:6883)
            at carbon.widget.RecyclerView.dispatchDrawWithHeader(RecyclerView.java:328)
            at carbon.widget.RecyclerView.dispatchDraw(RecyclerView.java:209)
            at android.view.View.draw(View.java:6883)
            at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:2997)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.View.draw(View.java:6883)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.View.draw(View.java:6883)
            at android.widget.FrameLayout.draw(FrameLayout.java:357)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.ViewGroup.drawChild(ViewGroup.java:1644)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1373)
            at android.view.View.draw(View.java:6883)
            at android.widget.FrameLayout.draw(FrameLayout.java:357)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1862)
            at android.view.ViewRoot.draw(ViewRoot.java:1522)
            at android.view.ViewRoot.performTraversals(ViewRoot.java:1258)
            at android.view.ViewRoot.handleMessage(ViewRoot.java:1859)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3683)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by ZieIony** [comment]
Did you try to add a map to a plain android.widget.FrameLayout?

Which Android version is your device running on?

**Comment by FunnyDevs** [comment]
My header_layout is a mapfragment inside a LinearLayout

Do you suggest to change LinearLayout with FrameLayout???

**Comment by ZieIony** [comment]
My suggestion is to replace RecyclerView with an android.widget.FrameLayout to check if it's an issue with Recycler or something else.

**Comment by FunnyDevs** [comment]
I have replace the recyclerview and now there is this error

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.geo.hoop/com.geo.hoop.MainActivity}: android.view.InflateException: Binary XML file line #46: Error inflating class fragment
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1647)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
            at android.app.ActivityThread.access$1500(ActivityThread.java:117)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3683)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #46: Error inflating class fragment
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:587)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
            at com.geo.hoop.MainActivity$PlaceholderFragment.onCreateView(MainActivity.java:189)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
            at com.geo.hoop.MainActivity.onStart(MainActivity.java:69)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1129)
            at android.app.Activity.performStart(Activity.java:3791)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1620)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
            at android.app.ActivityThread.access$1500(ActivityThread.java:117)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3683)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at com.geo.hoop.fragment.HomeFragment.onCreateView(HomeFragment.java:126)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:924)
            at android.support.v4.app.FragmentManagerImpl.onCreateView(FragmentManager.java:2194)
            at android.support.v4.view.LayoutInflaterCompatBase$FactoryWrapper.onCreateView(LayoutInflaterCompatBase.java:36)
            at android.view.LayoutInflater$FactoryMerger.onCreateView(LayoutInflater.java:133)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:563)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:623)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:408)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:320)
            at com.geo.hoop.MainActivity$PlaceholderFragment.onCreateView(MainActivity.java:189)
            at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
            at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
            at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
            at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:551)
            at com.geo.hoop.MainActivity.onStart(MainActivity.java:69)
            at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1129)
            at android.app.Activity.performStart(Activity.java:3791)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1620)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1663)
            at android.app.ActivityThread.access$1500(ActivityThread.java:117)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:931)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3683)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by ZieIony** [comment]
Seems like there's a problem with MapFragment declaration. I would start with as simple layout as possible. From there you can try to fix your MapFragment - check class names, go through tutorial once again, check all dependencies, etc. When you get the MapFragment working with that simple layout, add Recycler and other views.

**Comment by FunnyDevs** [comment]
Ok,thanks.

**Comment by ZieIony** [comment]
No answer for 7 days, I'm closing the issue.
