### ISSUE TITLE
java.lang.IndexOutOfBoundsException: -4, 1

### ISSUE THREAD

**Issue by Ludomancer** [ZieIony/Carbon#119]
Not entirely sure if it carbon related but, I don't have any other views other than carbon in that layout.

This happens randomly when I'm starting the activity with the below layout. The Activity does nothing at the moment.

``` xml
<?xml version="1.0" encoding="utf-8"?>
<carbon.widget.RelativeLayout
    android:id="@+id/root_layout"
    android:layout_width="wrap_content"
    android:layout_height="match_parent"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <android.support.v7.widget.Toolbar
    android:id="@+id/tool_bar"
    style="@style/Theme.AppName.Toolbar"
    android:layout_width="match_parent"
    android:layout_height="?attr/actionBarSize"
    app:theme="@style/Theme.AppName.Toolbar"/>

    <carbon.widget.FrameLayout
        android:id="@+id/card_view"
        android:layout_centerHorizontal="true"
        android:layout_height="fill_parent"
        android:layout_marginBottom="-20dp"
        android:layout_marginLeft="25dp"
        android:layout_marginRight="25dp"
        android:layout_marginTop="25dp"
        android:layout_width="fill_parent"
        android:layout_below="@+id/tool_bar"
        android:background="@color/cardview_light_background"
        >

        </carbon.widget.FrameLayout>

    <carbon.widget.LinearLayout
        android:layout_below="@+id/tool_bar"
        android:layout_height="wrap_content"
        android:layout_width="fill_parent"
        android:padding="10dp"
        android:id="@+id/fal_image_container"
        >

        <com.AppName.AppName.SquareImageViewFileLoader
            android:baselineAlignBottom="false"
            android:clickable="true"
            android:src="@drawable/profile_image_placeholder"
            android:cropToPadding="false"
            android:id="@+id/falImageButton1"
            android:layout_height="wrap_content"
            android:layout_weight="0.18"
            android:layout_width="0dp"
            app:carbon_cornerRadius="@dimen/button_corner_radius"
            android:scaleType="centerCrop"/>

        <com.AppName.AppName.SquareImageViewFileLoader
            android:baselineAlignBottom="false"
            android:clickable="true"
            android:src="@drawable/profile_image_placeholder"
            android:cropToPadding="false"
            android:id="@+id/falImageButton2"
            android:layout_height="wrap_content"
            android:layout_marginLeft="10dp"
            android:layout_weight="0.18"
            android:layout_width="0dp"
            app:carbon_cornerRadius="@dimen/button_corner_radius"
            android:scaleType="centerCrop"/>

        <com.AppName.AppName.SquareImageViewFileLoader
            android:baselineAlignBottom="false"
            android:clickable="true"
            android:src="@drawable/profile_image_placeholder"
            android:cropToPadding="false"
            android:id="@+id/falImageButton3"
            android:layout_height="wrap_content"
            android:layout_marginLeft="10dp"
            android:layout_weight="0.18"
            android:layout_width="0dp"
            app:carbon_cornerRadius="@dimen/button_corner_radius"
            android:scaleType="centerCrop"/>


    </carbon.widget.LinearLayout>

    <RelativeLayout
        android:layout_below="@+id/fal_image_container"
        android:layout_height="wrap_content"
        android:layout_width="match_parent"
        android:padding="10dp"
        android:id="@+id/comment_input_container"
        android:layout_alignLeft="@+id/card_view"
        android:layout_alignRight="@+id/card_view"
        >

        <carbon.widget.TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:textAppearance="?android:attr/textAppearanceSmall"
            android:text="Small Text"
            android:id="@+id/comment_receiver"
            android:layout_marginLeft="4dp"/>

        <EditText
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:id="@+id/comment_text"
        android:layout_centerHorizontal="true"
        android:background="@drawable/abc_edit_text_material"
        android:editable="true"
        android:enabled="true"
        android:inputType="text|textMultiLine"
        android:layout_toLeftOf="@+id/comment_send_button"
        android:hint="Science Biatch!"
        android:layout_below="@+id/comment_receiver"
        android:layout_marginTop="-10dp"
        android:maxLength="750"
            />

        <ImageButton
            android:layout_width="40dp"
            android:layout_height="40dp"
            android:id="@+id/comment_send_button"
            android:layout_centerVertical="true"
            android:layout_alignParentRight="true"
            android:background="@drawable/ic_action_send_now"
            android:adjustViewBounds="false"
            android:layout_alignBottom="@+id/comment_text"
            android:layout_marginBottom="5dp"/>

    </RelativeLayout>

    <FrameLayout
        xmlns:android="http://schemas.android.com/apk/res/android"
        xmlns:app="http://schemas.android.com/apk/res-auto"
        android:id="@+id/overlay_frame"
        android:layout_height="match_parent"
        android:layout_width="match_parent"
        android:background="@color/carbon_black_54"

        android:elevation="999dp"
        android:clickable="true"
        android:visibility="gone">

    </FrameLayout>

</carbon.widget.RelativeLayout>
```

 java.lang.IndexOutOfBoundsException: -4, 1
            at android.text.PackedIntVector.getValue(PackedIntVector.java:70)
            at android.text.DynamicLayout.getLineTop(DynamicLayout.java:592)
            at android.widget.TextView.onMeasure(TextView.java:6433)
            at android.view.View.measure(View.java:16514)
            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
            at android.view.View.measure(View.java:16514)
            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
            at android.view.View.measure(View.java:16514)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
            at android.view.View.measure(View.java:16514)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1450)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
            at android.view.View.measure(View.java:16514)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:16514)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1450)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
            at android.view.View.measure(View.java:16514)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2563)
            at android.view.View.measure(View.java:16514)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1915)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1109)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1291)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5603)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
            at android.view.Choreographer.doFrame(Choreographer.java:544)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5158)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)
07-21 00:47:51.030  19178-19178/com.AppName.AppName E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.AppName.AppName, PID: 19178
    java.lang.IndexOutOfBoundsException: -4, 1
            at android.text.PackedIntVector.getValue(PackedIntVector.java:70)
            at android.text.DynamicLayout.getLineTop(DynamicLayout.java:592)
            at android.widget.TextView.onMeasure(TextView.java:6433)
            at android.view.View.measure(View.java:16514)
            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
            at android.view.View.measure(View.java:16514)
            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:719)
            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:455)
            at android.view.View.measure(View.java:16514)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:124)
            at android.view.View.measure(View.java:16514)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1450)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
            at android.view.View.measure(View.java:16514)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at android.view.View.measure(View.java:16514)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1450)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
            at android.view.View.measure(View.java:16514)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5125)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2563)
            at android.view.View.measure(View.java:16514)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1915)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1109)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1291)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5603)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
            at android.view.Choreographer.doFrame(Choreographer.java:544)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5158)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by ZieIony** [comment]
It doesn't look like an issue with Carbon. Did you try to reproduce the issue with minimal app? To do that copy your project and remove things until the project works. It should give us a hint what's may be going on.

**Comment by Ludomancer** [comment]
I will try to take a look at it, and update here if I can find some free time.

**Comment by ZieIony** [comment]
no update for 22 days, I'm closing the issue
