### ISSUE TITLE
InflateException when trying to inflate Layout with Carbon.Widget.Button

### ISSUE THREAD

**Issue by borgwald** [ZieIony/Carbon#120]
```
@Override
    public ProfileAdapter.ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {

        switch (viewType){
            case 0:
                View headerView = mInflater.inflate(R.layout.padding, parent, false);
                return new HeaderViewHolder(headerView);
            case 2:
                View staticMapView = mInflater.inflate(R.layout.static_map_item, parent, false);
                return new ImageViewHolder(staticMapView);
            default:
                View itemView = mInflater.inflate(mItemResourceId, parent, false);
                return new ViewHolder(itemView);
        }
    }
```

static_map_item.xml:

```
<tk.zielony.carbon.widget.LinearLayout 
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:padding="15dp">
    <tk.zielony.carbon.widget.Button
        style="@style/carbon_Button.Flat"
        android:id="@+id/post_button"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_gravity="right"
        android:layout_margin="@dimen/carbon_padding"
        android:text="Set Homezone" />
    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
        <ImageView
            android:id="@+id/static_map"
            android:layout_width="match_parent"
            android:layout_height="200dp" />
        <ImageView
            android:id="@+id/homezone_marker"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />
        <ImageView
            android:id="@+id/static_map_marker"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content" />
    </FrameLayout>
</tk.zielony.carbon.widget.LinearLayout>
```

Error:

android.view.InflateException: Binary XML file line #8: Error inflating class tk.zielony.carbon.widget.Button

**Comment by ZieIony** [comment]
Could you post the full stacktrace?

**Comment by borgwald** [comment]
```
07-23 21:27:50.565  31502-31502/? E/dalvikvm﹕ Could not find class 'tk.zielony.carbon.drawable.RippleDrawableLollipop', referenced from method tk.zielony.carbon.Carbon.initRippleDrawable
07-23 21:27:50.600  31502-31502/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.monarch.monarchapp, PID: 31502
    android.view.InflateException: Binary XML file line #9: Error inflating class tk.zielony.carbon.widget.Button
            at android.view.LayoutInflater.createView(LayoutInflater.java:626)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
            at com.monarch.monarchapp.adapter.ProfileAdapter.onCreateViewHolder(ProfileAdapter.java:67)
            at com.monarch.monarchapp.adapter.ProfileAdapter.onCreateViewHolder(ProfileAdapter.java:22)
            at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:5062)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4368)
            at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:4278)
            at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:1947)
            at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1359)
            at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1322)
            at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:556)
            at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2673)
            at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:2971)
            at android.view.View.layout(View.java:15859)
            at android.view.ViewGroup.layout(ViewGroup.java:4902)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15859)
            at android.view.ViewGroup.layout(ViewGroup.java:4902)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15859)
            at android.view.ViewGroup.layout(ViewGroup.java:4902)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15859)
            at android.view.ViewGroup.layout(ViewGroup.java:4902)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15859)
            at android.view.ViewGroup.layout(ViewGroup.java:4902)
            at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1677)
            at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1531)
            at android.widget.LinearLayout.onLayout(LinearLayout.java:1440)
            at android.view.View.layout(View.java:15859)
            at android.view.ViewGroup.layout(ViewGroup.java:4902)
            at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
            at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
            at android.view.View.layout(View.java:15859)
            at android.view.ViewGroup.layout(ViewGroup.java:4902)
            at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2376)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2089)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1264)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6632)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
            at android.view.Choreographer.doCallbacks(Choreographer.java:613)
            at android.view.Choreographer.doFrame(Choreographer.java:583)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5635)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:129
```

**Comment by borgwald** [comment]
i have another inflationerror in another layout when using carbon.widget.button. its a normal layout without inflating something by myself. Maybe this is better:

edit_profile.xml:

```
<tk.zielony.carbon.widget.RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@android:color/white"
        android:padding="@dimen/carbon_padding">
        <LinearLayout android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:id="@+id/header"
            android:orientation="vertical">
            <LinearLayout android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:gravity="center_horizontal"
                android:padding="10dp"
                android:layout_gravity="center_vertical"
                android:layout_alignParentTop="true"
                android:orientation="vertical">
                <LinearLayout android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:padding="10dp"
                    android:orientation="horizontal">
                    <TextView android:layout_width="wrap_content"
                        android:layout_height="match_parent"
                        android:text="Status: "
                        android:textStyle="bold"
                        android:textSize="15sp"
                        android:textColor="@color/darkGrey"
                        android:gravity="center_vertical"/>
                    <EditText android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:layout_marginLeft="10dp"
                        android:hint="change your Status"
                        android:textSize="15sp"
                        android:gravity="center_vertical"
                        android:id="@+id/status"/>
                </LinearLayout>
                <LinearLayout android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:padding="10dp"
                    android:orientation="horizontal">
                    <TextView android:layout_width="wrap_content"
                        android:layout_height="match_parent"
                        android:text="Day of Birth: "
                        android:textStyle="bold"
                        android:textSize="15sp"
                        android:textColor="@color/darkGrey"
                        android:gravity="center_vertical"/>
                    <EditText android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:layout_marginLeft="10dp"
                        android:hint="your Birthday"
                        android:textSize="15sp"
                        android:gravity="center_vertical"
                        android:id="@+id/birthday"/>
                </LinearLayout>
                <LinearLayout android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:padding="10dp"
                    android:orientation="horizontal">
                    <TextView android:layout_width="wrap_content"
                        android:layout_height="match_parent"
                        android:text="Gender: "
                        android:textStyle="bold"
                        android:textSize="15sp"
                        android:textColor="@color/darkGrey"
                        android:gravity="center_vertical"/>
                    <EditText android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:layout_marginLeft="10dp"
                        android:hint="Gender"
                        android:textSize="15sp"
                        android:gravity="center_vertical"
                        android:id="@+id/gender"/>
                </LinearLayout>
                <LinearLayout android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:padding="10dp"
                    android:orientation="horizontal">
                    <TextView android:layout_width="wrap_content"
                        android:layout_height="match_parent"
                        android:text="Interests: "
                        android:textStyle="bold"
                        android:textSize="15sp"
                        android:textColor="@color/darkGrey"
                        android:gravity="center_vertical"/>
                    <EditText android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:layout_marginLeft="10dp"
                        android:hint="your Interests"
                        android:textSize="15sp"
                        android:gravity="center_vertical"
                        android:id="@+id/interests"/>
                </LinearLayout>
                <TextView
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:minHeight="?attr/actionBarSize"
                    android:layout_marginTop="10dp"
                    android:layout_marginBottom="10dp"
                    android:padding="10dp"
                    android:text="Change your Picture and Background"
                    android:textStyle="bold"
                    android:textSize="15sp"
                    android:textColor="@color/darkGrey"
                    android:gravity="center_vertical"
                    android:background="@color/lighter_grey"/>
                <LinearLayout
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:orientation="horizontal">
                    <ImageView
                        android:layout_width="96dp"
                        android:layout_height="96dp"
                        android:id="@+id/profile_picture"
                        android:layout_marginRight="20dp"/>
                    <ImageView
                        android:layout_width="96dp"
                        android:layout_height="96dp"
                        android:id="@+id/profile_header_background"
                        android:scaleType="centerCrop"/>
                </LinearLayout>
            </LinearLayout>
        </LinearLayout>
        <tk.zielony.carbon.widget.Button
            android:id="@+id/post_profile"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginBottom="@dimen/carbon_padding"
            android:layout_marginTop="@dimen/carbon_padding"
            android:background="#ffffffff"
            android:text="Post"
            android:textAppearance="?attr/carbon_textAppearanceButton"
            app:carbon_rippleColor="#42FF5252" />
    </tk.zielony.carbon.widget.RelativeLayout>
```

Error:

```
07-23 21:32:13.125  31892-31892/? E/dalvikvm﹕ Could not find class 'tk.zielony.carbon.drawable.RippleDrawableLollipop', referenced from method tk.zielony.carbon.Carbon.initRippleDrawable
07-23 21:32:14.560  31892-31892/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.monarch.monarchapp, PID: 31892
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.monarch.monarchapp/com.monarch.monarchapp.EditProfileActivity}: android.view.InflateException: Binary XML file line #133: Error inflating class tk.zielony.carbon.widget.Button
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2436)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
            at android.app.ActivityThread.access$900(ActivityThread.java:170)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5635)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: android.view.InflateException: Binary XML file line #133: Error inflating class tk.zielony.carbon.widget.Button
            at android.view.LayoutInflater.createView(LayoutInflater.java:626)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at com.monarch.monarchapp.EditProfileActivity.onCreate(EditProfileActivity.java:67)
            at android.app.Activity.performCreate(Activity.java:5585)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
            at android.app.ActivityThread.access$900(ActivityThread.java:170)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5635)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.reflect.InvocationTargetException
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.createView(LayoutInflater.java:600)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at com.monarch.monarchapp.EditProfileActivity.onCreate(EditProfileActivity.java:67)
            at android.app.Activity.performCreate(Activity.java:5585)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
            at android.app.ActivityThread.access$900(ActivityThread.java:170)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5635)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.RuntimeException: native typeface cannot be made
            at android.graphics.Typeface.<init>(Typeface.java:335)
            at android.graphics.Typeface.createFromAsset(Typeface.java:309)
            at tk.zielony.carbon.internal.TypefaceUtils.getTypeface(TypefaceUtils.java:15)
            at tk.zielony.carbon.widget.Button.setTextAppearance(Button.java:131)
            at tk.zielony.carbon.widget.Button.init(Button.java:79)
            at tk.zielony.carbon.widget.Button.<init>(Button.java:68)
            at tk.zielony.carbon.widget.Button.<init>(Button.java:63)
            at java.lang.reflect.Constructor.constructNative(Native Method)
            at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
            at android.view.LayoutInflater.createView(LayoutInflater.java:600)
            at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:702)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:761)
            at android.view.LayoutInflater.rInflate(LayoutInflater.java:769)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:498)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:398)
            at android.view.LayoutInflater.inflate(LayoutInflater.java:354)
            at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:249)
            at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:106)
            at com.monarch.monarchapp.EditProfileActivity.onCreate(EditProfileActivity.java:67)
            at android.app.Activity.performCreate(Activity.java:5585)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2400)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
            at android.app.ActivityThread.access$900(ActivityThread.java:170)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1304)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:146)
            at android.app.ActivityThread.main(ActivityThread.java:5635)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by borgwald** [comment]
somehow he did not find the asset-folder from Typeface.createFromAsset(context.getAssets(), path), because he is looking in the asset-folder from my own app-package.

i copied the fonts to my asset-folder and now it is working.

**Comment by ZieIony** [comment]
That's weird, I had no reports regarding this issue before. Let's keep this issue open, so I can investigate it.

**Comment by NeverGivinUp** [comment]
Works for me. I don't need to copy the fonts. Are you using a current build environment (Android Studio version, android plugin version, gradle version)?

**Comment by borgwald** [comment]
i am using the latest android studio.i think its because i don't use the gradle build system. i am using ant.

**Comment by ZieIony** [comment]
Gradle merges resources when building a project with dependencies. Old type libraries had issues with resources. This project is not really intended to be used as a library for ant builds. I'm happy that you've found the solution and I don't think that I can do anything more about that.
