### ISSUE TITLE
double packaged class in UI test 

### ISSUE THREAD

**Issue by NeverGivinUp** [ZieIony/Carbon#121]
This is a stacktrace I get, when running a UI test:

``` stacktrace
Running tests
Test running started
java.lang.IllegalAccessError: Class ref in pre-verified class resolved to unexpected implementation
at carbon.shadow.ShadowGenerator.generateShadow(ShadowGenerator.java:85)
at carbon.widget.ImageView.getShadow(ImageView.java:379)
at carbon.widget.RelativeLayout.drawChild(RelativeLayout.java:133)
```

ShadowGenerator 85 is the line `renderScript = RenderScript.create(view.getContext());` in the method 

``` Java
 public static Shadow generateShadow(View view, float elevation) {
        if (!software && renderScript == null) {
            try {
                renderScript = RenderScript.create(view.getContext());
                blurShader = ScriptIntrinsicBlur.create(renderScript, Element.U8_4(renderScript));
            } catch (RSRuntimeException ignore) {
                software = true;
            }
        }
...
```

From what I understand from [here}(http://www.sinking.in/blog/android-dependency-double-trouble/), this is because carbon (or some library used by it) get packaged twice -- once in the app and once in the test.

While I am waiting for a carbon update with the changes in the FloatingActionButton and VectorDrawable, I have downloaded and adjusted the carbon source and reference it as a module. Thus I cannot treat it as a provided jar. Bar that, I have all libraries used by carbon in my gradle settings.

Any ideas on how to get it running anyway?

Here is my settings.gradle  and my current test case

``` gradle
apply plugin: 'com.android.application'

android {
    signingConfigs {
        generalVahdatSigningConfig {
            keyAlias 'com.vahdat'
        }
    }

    compileSdkVersion 22
    buildToolsVersion '22.0.1'
    defaultConfig {
        applicationId "com.vahdat.gastricbypasssupport"
        minSdkVersion 18
        targetSdkVersion 22

        renderscriptTargetApi 22
        renderscriptSupportModeEnabled true

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-project.txt'
            signingConfig signingConfigs.generalVahdatSigningConfig
            debuggable true
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
    sourceSets { debug { java.srcDirs = ['src/debug/java', 'src/test/java/'] } }
    productFlavors {
        }
    }

configurations {
    provided
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile('com.afollestad:material-dialogs:0.7.7.0') {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    compile('com.rengwuxian.materialedittext:library:2.1.4') {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    compile('com.android.support:cardview-v7:22.1.1') {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    compile 'joda-time:joda-time:2.8.1'
    compile('com.android.support:gridlayout-v7:22.2.1') {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    compile('com.android.support:appcompat-v7:22.2.1') {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    compile('com.android.support:recyclerview-v7:22.2.1') {
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    compile 'com.readystatesoftware.sqliteasset:sqliteassethelper:2.0.1'
    compile 'com.squareup:android-times-square:1.6.2@aar'
    compile 'com.caverock:androidsvg:1.2.1'
    compile(project(':carbon')) {
        // exclude all dependencies of carbon, that we depend upon ourselves, to avoid package collisions when using more current versions
        exclude group: 'com.android.support', module: 'appcompat-v7'
        exclude group: 'com.android.support', module: 'support-v4'
        exclude group: 'com.android.support', module: 'support-annotations'
        exclude group: 'com.android.support', module: 'gridlayout-v7'
        exclude group: 'com.android.support', module: 'recyclerview-v7'
        exclude group: 'com.android.support.v8', module: 'renderscript'
        exclude group: 'com.caverock', module: 'androidsvg'
        //exclude group 'com.nineoldandroids' module: 'library' //do not exclude nineoldandroids, as we don't use it
    }
    //    compile project(':gastricBypassSupport')
    androidTestCompile('com.android.support.test:runner:0.3') {
        exclude group: 'com.android.support', module: 'support-v4'
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    // Set this dependency to use JUnit 4 rules
    androidTestCompile('com.android.support.test:rules:0.3') {
        exclude group: 'com.android.support', module: 'support-v4'
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    // Set this dependency to build and run Espresso tests
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2') {
        exclude group: 'com.android.support', module: 'support-v4'
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    // Set this dependency to build and run UI Automator tests
    androidTestCompile('com.android.support.test.uiautomator:uiautomator-v18:2.1.1') {
        exclude group: 'com.android.support', module: 'support-v4'
        exclude group: 'com.android.support', module: 'support-annotations'
    }
    compile 'com.android.support:support-annotations:22.2.1'
}

// Android's version of sourceSets.main.compileClasspath
android.applicationVariants.each { variant ->
    variant.javaCompile.classpath += configurations.provided
}
```

``` Java
package com.vahdat.gastricbypasssupport;

import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageManager;
import android.content.pm.ResolveInfo;
import android.support.test.InstrumentationRegistry;
import android.support.test.runner.AndroidJUnit4;
import android.support.test.uiautomator.By;
import android.support.test.uiautomator.UiDevice;
import android.support.test.uiautomator.UiObject2;
import android.support.test.uiautomator.Until;

import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.io.File;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.CoreMatchers.notNullValue;
import static org.junit.Assert.assertThat;
import static org.junit.Assert.assertTrue;

@RunWith(AndroidJUnit4.class)
public class TestCase {
    private static final String PACKAGE = "com.vahdat.gastricbypasssupport";
    private static final int LAUNCH_TIMEOUT = 5000;

    private static UiDevice mDevice;

    @Before
    public  void startMainActivityFromHomeScreen() {
        // Initialize UiDevice instance
        mDevice = UiDevice.getInstance(InstrumentationRegistry.getInstrumentation());
        // Start from the home screen
        mDevice.pressHome();

        // Wait for launcher
        final String launcherPackage = getLauncherPackageName();
        assertThat(launcherPackage, notNullValue());
        mDevice.wait(Until.hasObject(By.pkg(launcherPackage).depth(0)), LAUNCH_TIMEOUT);

        // Launch the app
        Context context = InstrumentationRegistry.getContext();
        final Intent intent = context.getPackageManager().getLaunchIntentForPackage(PACKAGE);
        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK);    // Clear out any previous instances
        context.startActivity(intent);

        // Wait for the app to appear
        mDevice.wait(Until.hasObject(By.pkg(PACKAGE).depth(0)), LAUNCH_TIMEOUT);
    }

    @Test
    public void run() {
        assertThat(mDevice, notNullValue());
        waitForMainActivity();
        selectFromMainMenu("Nahrungsaufnahme");

    }

    public void waitForMainActivity() {
        assertTrue(mDevice.wait(Until.hasObject(By.text("laden")), LAUNCH_TIMEOUT));
        photo();
        assertTrue(mDevice.wait(Until.gone(By.text("laden")), Long.MAX_VALUE));
        photo();
        final UiObject2 timeTakenForEatingDialogPositiveButton = mDevice.findObject(By.text("Ich habe genug und oft genug gegessen."));
        if (timeTakenForEatingDialogPositiveButton != null)
            timeTakenForEatingDialogPositiveButton.click();

        selectMainFragment("Rückblick");
    }

    private void photo() {
        mDevice.takeScreenshot(new File("/storage/emulated/legacy/screenshot.jpg"));
    }

    private void selectFromMainMenu(String mainMenuEntry) {
        openMainMenu();
        mDevice.findObject(By.res("com.vahdat.gastricbypasssupport:id/menu_item").hasChild(By.text(mainMenuEntry))).click();
        selectMainFragment(mainMenuEntry);
    }

    private void openMainMenu() {
        assertTrue(isInMainActivity());
        if (!isInMainMenu()) {
            final UiObject2 actionBarMenuIcon = mDevice.findObject(By.desc("Menü öffnen"));
            assertThat(actionBarMenuIcon, notNullValue());
            actionBarMenuIcon.click();
            assertMainMenu();
        }
    }

    private void assertMainMenu() {
        photo();
        assertTrue(mDevice.wait(Until.hasObject(By.res("com.vahdat.gastricbypasssupport:id/gastric_bypass")), LAUNCH_TIMEOUT));
        photo();
    }

    private void selectMainFragment(String mainFragmentName) {
        photo();
        assertTrue(mDevice.wait(Until.hasObject(By.res("com.vahdat.gastricbypasssupport:id/custom_toolbar_title").text(mainFragmentName)), LAUNCH_TIMEOUT));
        photo();
        assertTrue(isInMainActivity());
        photo();
    }

    private boolean isInMainActivity() {
        return mDevice.findObject(By.desc("Menü öffnen")) != null || isInMainMenu();
    }

    private boolean isInMainMenu() {
        return mDevice.findObject(By.res("com.vahdat.gastricbypasssupport:id/gastric_bypass")) != null;
    }

    /**
     * Uses package manager to find the package name of the device launcher. Usually this package
     * is "com.android.launcher" but can be different at times. This is a generic solution which
     * works on all platforms.`
     */
    private static String getLauncherPackageName() {
        // Create launcher Intent
        final Intent intent = new Intent(Intent.ACTION_MAIN);
        intent.addCategory(Intent.CATEGORY_HOME);

        // Use PackageManager to get the launcher package name
        PackageManager pm = InstrumentationRegistry.getContext().getPackageManager();
        ResolveInfo resolveInfo = pm.resolveActivity(intent, PackageManager.MATCH_DEFAULT_ONLY);
        return resolveInfo.activityInfo.packageName;
    }

}

```

**Comment by NeverGivinUp** [comment]
Closing this, as it has not been an issue for a long time. I must have changed something that made it work.
