### ISSUE TITLE
Carbon with Proguard

### ISSUE THREAD

**Issue by singhdd93** [ZieIony/Carbon#172]
Hi,
I am using Carbon with proguard. The app works great when proguard is disabled.But with proguard enabled, I am getting on a Lollipop Device

```
at carbon.widget.RecyclerView.ensureTopGlow(Unknown Source)
    at carbon.widget.RecyclerView.dispatchTouchEvent(Unknown Source)
```

And on ASUS Zenfone (running 4.4), It crashes with renderScript Error. I forgot to keep backup of stacktrace when I tested on friends device

Edit: Got the log from play store and retraced it

```
java.lang.NoSuchMethodError: no static or non-static method "Landroid/support/v8/renderscript/RenderScript;.nDeviceDestroy(J)V"
    at java.lang.Runtime.nativeLoad(Native Method)
    at java.lang.Runtime.doLoad(Runtime.java:421)
    at java.lang.Runtime.loadLibrary(Runtime.java:362)
    at java.lang.System.loadLibrary(System.java:526)
    at android.support.v8.renderscript.RenderScript.nAllocationCreateBitmapBackedAllocation(Unknown Source)
                                                 nIncElementCreate
                                                 nIncTypeCreate
                                                 validate
                                                 internalCreate
    at android.support.v8.renderscript.RenderScript.isUseNative(Unknown Source)
                                                 setupNative
                                                 nContextCreate
                                                 nObjDestroy
                                                 nElementCreate
                                                 nTypeCreate
                                                 nAllocationCreateTyped
                                                 nAllocationCreateFromBitmap
                                                 nAllocationCopyToBitmap
                                                 nScriptForEach
                                                 nScriptSetVarF
                                                 nScriptSetVarObj
                                                 nScriptIntrinsicCreate
                                                 nIncContextCreate
                                                 nIncAllocationCreateTyped
                                                 create
                                                 create
                                                 create
                                                 create
    at android.support.v8.renderscript.RenderScript.isUseNative(Unknown Source)
                                                 setupNative
                                                 nContextCreate
                                                 nObjDestroy
                                                 nElementCreate
                                                 nTypeCreate
                                                 nAllocationCreateTyped
                                                 nAllocationCreateFromBitmap
                                                 nAllocationCopyToBitmap
                                                 nScriptForEach
                                                 nScriptSetVarF
                                                 nScriptSetVarObj
                                                 nScriptIntrinsicCreate
                                                 nIncContextCreate
                                                 nIncAllocationCreateTyped
                                                 create
                                                 create
                                                 create
                                                 create
    at android.support.v8.renderscript.RenderScript.isUseNative(Unknown Source)
                                                 setupNative
                                                 nContextCreate
                                                 nObjDestroy
                                                 nElementCreate
                                                 nTypeCreate
                                                 nAllocationCreateTyped
                                                 nAllocationCreateFromBitmap
                                                 nAllocationCopyToBitmap
                                                 nScriptForEach
                                                 nScriptSetVarF
                                                 nScriptSetVarObj
                                                 nScriptIntrinsicCreate
                                                 nIncContextCreate
                                                 nIncAllocationCreateTyped
                                                 create
                                                 create
                                                 create
                                                 create
    at android.support.v8.renderscript.RenderScript.isUseNative(Unknown Source)
                                                 setupNative
                                                 nContextCreate
                                                 nObjDestroy
                                                 nElementCreate
                                                 nTypeCreate
                                                 nAllocationCreateTyped
                                                 nAllocationCreateFromBitmap
                                                 nAllocationCopyToBitmap
                                                 nScriptForEach
                                                 nScriptSetVarF
                                                 nScriptSetVarObj
                                                 nScriptIntrinsicCreate
                                                 nIncContextCreate
                                                 nIncAllocationCreateTyped
                                                 create
                                                 create
                                                 create
                                                 create
    at carbon.shadow.ShadowGenerator.blur(Unknown Source)
                                  generateShadow
    at carbon.widget.Button.getShadow(Unknown Source)
    at carbon.widget.LinearLayout.drawChild(Unknown Source)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2961)
    at carbon.widget.LinearLayout.dispatchDraw(Unknown Source)
    at android.view.View.draw(View.java:14743)
    at carbon.widget.LinearLayout.draw(Unknown Source)
    at android.view.View.getDisplayList(View.java:13636)
    at android.view.View.getDisplayList(View.java:13678)
    at android.view.View.draw(View.java:14457)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3117)
    at carbon.widget.LinearLayout.drawChild(Unknown Source)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2961)
    at carbon.widget.LinearLayout.dispatchDraw(Unknown Source)
    at android.view.View.draw(View.java:14743)
    at carbon.widget.LinearLayout.draw(Unknown Source)
    at android.view.View.getDisplayList(View.java:13636)
    at android.view.View.getDisplayList(View.java:13678)
    at android.view.View.draw(View.java:14457)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3117)
    at carbon.widget.LinearLayout.drawChild(Unknown Source)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2961)
    at carbon.widget.LinearLayout.dispatchDraw(Unknown Source)
    at android.view.View.draw(View.java:14743)
    at carbon.widget.LinearLayout.draw(Unknown Source)
    at android.view.View.getDisplayList(View.java:13636)
    at android.view.View.getDisplayList(View.java:13678)
    at android.view.View.draw(View.java:14457)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3117)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2954)
    at android.view.View.draw(View.java:14743)
    at android.widget.FrameLayout.draw(FrameLayout.java:472)
    at android.view.View.getDisplayList(View.java:13636)
    at android.view.View.getDisplayList(View.java:13678)
    at android.view.View.draw(View.java:14457)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3117)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2954)
    at android.view.View.getDisplayList(View.java:13631)
    at android.view.View.getDisplayList(View.java:13678)
    at android.view.View.draw(View.java:14457)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3117)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2954)
    at android.view.View.getDisplayList(View.java:13631)
    at android.view.View.getDisplayList(View.java:13678)
    at android.view.View.draw(View.java:14457)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3117)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2954)
    at android.view.View.getDisplayList(View.java:13631)
    at android.view.View.getDisplayList(View.java:13678)
    at android.view.View.draw(View.java:14457)
    at android.view.ViewGroup.drawChild(ViewGroup.java:3117)
    at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2954)
    at android.view.View.draw(View.java:14743)
    at android.widget.FrameLayout.draw(FrameLayout.java:472)
    at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2329)
    at android.view.View.getDisplayList(View.java:13636)
    at android.view.View.getDisplayList(View.java:13678)
    at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
    at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
    at android.view.ViewRootImpl.draw(ViewRootImpl.java:2401)
    at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2273)
    at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1903)
    at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1020)
    at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5762)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:771)
    at android.view.Choreographer.doCallbacks(Choreographer.java:574)
    at android.view.Choreographer.doFrame(Choreographer.java:544)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:757)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:149)
    at android.app.ActivityThread.main(ActivityThread.java:5257)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ZieIony** [comment]
Is the issue with RenderScript also caused by ProGuard?

**Comment by singhdd93** [comment]
Yes
And sorry for late reply. I was travelling and couldn't check back.

**Comment by ZieIony** [comment]
No problem. With this detailed info I should be able to reproduce your issue. First one is probably related to overriding hidden methods and the second one to native methods.

**Comment by ayalma** [comment]
```
java.lang.NoSuchMethodError: no static or non-static method "Landroid/support/v8/renderscript/RenderScript;.nDeviceDestroy(J)V"
                                                       at java.lang.Runtime.nativeLoad(Native Method)
                                                       at java.lang.Runtime.doLoad(Runtime.java:421)
                                                       at java.lang.Runtime.loadLibrary(Runtime.java:362)
                                                       at java.lang.System.loadLibrary(System.java:555)
                                                       at android.support.v8.renderscript.RenderScript.b(Unknown Source)
                                                       at android.support.v8.renderscript.RenderScript.a(Unknown Source)
                                                       at android.support.v8.renderscript.RenderScript.a(Unknown Source)
                                                       at android.support.v8.renderscript.RenderScript.a(Unknown Source)
                                                       at android.support.v8.renderscript.RenderScript.a(Unknown Source)
                                                       at carbon.shadow.ShadowGenerator.generateShadow(Unknown Source)
                                                       at carbon.widget.LinearLayout.getShadow(Unknown Source)
                                                       at carbon.widget.FrameLayout.drawChild(Unknown Source)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2956)
                                                       at carbon.widget.FrameLayout.dispatchDraw(Unknown Source)
                                                       at android.view.View.draw(View.java:14523)
                                                       at android.widget.FrameLayout.draw(FrameLayout.java:472)
                                                       at carbon.widget.FrameLayout.draw(Unknown Source)
                                                       at android.view.View.getDisplayList(View.java:13404)
                                                       at android.view.View.getDisplayList(View.java:13446)
                                                       at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1609)
                                                       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1484)
                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2476)
                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2340)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1963)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1053)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5959)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:780)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:593)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:562)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:766)
                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:136)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5392)
                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:864)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:680)
                                                       at dalvik.system.NativeStart.main(Native Method)
```

 i faced with this error too in 4.4.2 emulator with progard in release version of my app.

**Comment by ayalma** [comment]
and i add this line to  app module  proguard-rules.pro  file

```
-keep class android.support.v8.** { *; }
```

and problem solved.

**Comment by ZieIony** [comment]
RecyclerView::ensureTopGlow() is no longer used by Carbon.

ProGuard config for RenderScript:

```
-keepclasseswithmembernames class * {
    native <methods>;
}

-keep class android.support.v8.renderscript.** { *; }
```
