### ISSUE TITLE
EditText crashes on LDPI devices

### ISSUE THREAD

**Issue by ZieIony** [ZieIony/Carbon#182]
```
java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:667)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:649)
       at carbon.widget.EditText.initEditText(EditText.java:201)
       at carbon.widget.EditText.<init>(EditText.java:129)
```

**Comment by ZieIony** [comment]
fixed
