### ISSUE TITLE
IncompatibleClassChangeError

### ISSUE THREAD

**Issue by HectorFGarcia** [ZieIony/Carbon#217]
I'm getting this crash 

```
java.lang.IncompatibleClassChangeError: carbon.drawable.EdgeEffectCompat
```

everytime I choose any option in a Spinner.

Tested on a Nexus 5 (2013) with Marshmellow 6.0.1 and Carbon 0.11.

Full trace:

```
at carbon.widget.RecyclerView.ensureTopGlow(RecyclerView.java:136)
at carbon.widget.RecyclerView.dispatchTouchEvent(RecyclerView.java:183)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
at carbon.widget.FrameLayout.dispatchTouchEvent(FrameLayout.java:279)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
at carbon.widget.FrameLayout.dispatchTouchEvent(FrameLayout.java:279)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:1968)
at android.view.View.dispatchPointerEvent(View.java:9520)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:323)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by ZieIony** [comment]
Looks like version conflict. Check if support and appcompat lib versions are matching and then rebuild the project.

**Comment by HectorFGarcia** [comment]
```
compile 'com.android.support:appcompat-v7:23.2.1'
compile 'com.android.support:support-v4:23.2.1'
compile 'com.android.support:design:23.2.1'
compile 'com.android.support:recyclerview-v7:23.2.1'
```

I tried to clean & rebuild but nothing changed.

**Comment by ZieIony** [comment]
Carbon 0.11.0 uses older EdgeEffect classes. In 23.2.1 EdgeEffect has changed, is private and apparently is causing conflicts. You need to use same AppCompat version in all modules. Either you have to use older Google libs in your project or update Carbon to the version with libs 23.2.1.

In 0.11.0 Carbon was using libs 23.1.1

**Comment by HectorFGarcia** [comment]
Downgrade to 23.1.1 fix it.

**Comment by HectorFGarcia** [comment]
Wait, I upgraded Carbon to 0.12 and I still have the same problem :(

**Comment by ZieIony** [comment]
Carbon 0.12.0 uses 23.1.1, so it should be fine. Maybe it's a conflict with one of other libraries you're using. I've experienced your issue before in one of my projects and its root is pretty clear. See: http://stackoverflow.com/questions/1980452/what-causes-java-lang-incompatibleclasschangeerror

**Comment by HectorFGarcia** [comment]
Oh, ok. I'll wait until you update Carbon to 23.2.1 :)
