### ISSUE TITLE
Exception dispatching input event

### ISSUE THREAD

**Issue by ayalma** [ZieIony/Carbon#233]
hi i using recyclerView and faced with this issue when i clicking on all recyclerView's on my app even NavigationView .

this is my stack trace on emulator with api 23 : 

```
04-08 18:53:53.480 3299-3299/? I/art: Not late-enabling -Xcheck:jni (already on)
04-08 18:53:53.480 3299-3299/? I/art: Late-enabling JIT
04-08 18:53:53.490 3299-3299/? I/art: JIT created with code_cache_capacity=2MB compile_threshold=1000
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication W/art: Before Android 4.1, method void carbon.widget.RecyclerView.ensureBottomGlow() would have incorrectly overridden the package-private method in android.support.v7.widget.RecyclerView
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication W/art: Before Android 4.1, method void carbon.widget.RecyclerView.ensureLeftGlow() would have incorrectly overridden the package-private method in android.support.v7.widget.RecyclerView
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication W/art: Before Android 4.1, method void carbon.widget.RecyclerView.ensureRightGlow() would have incorrectly overridden the package-private method in android.support.v7.widget.RecyclerView
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication W/art: Before Android 4.1, method void carbon.widget.RecyclerView.ensureTopGlow() would have incorrectly overridden the package-private method in android.support.v7.widget.RecyclerView
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication W/art: Before Android 4.1, method void carbon.widget.RecyclerView.invalidateGlows() would have incorrectly overridden the package-private method in android.support.v7.widget.RecyclerView
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.660 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:54.700 3299-3328/ayalma.ir.myapplication D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
04-08 18:53:54.720 3299-3299/ayalma.ir.myapplication W/FragmentManager: moveToState: Fragment state for LowsFragment{83e5ce6 #0 id=0x7f0d008e android:switcher:2131558542:1} not updated inline; expected state 3 found 2
04-08 18:53:54.740 3299-3328/ayalma.ir.myapplication I/OpenGLRenderer: Initialized EGL, version 1.4
04-08 18:53:54.760 3299-3328/ayalma.ir.myapplication W/EGL_emulation: eglSurfaceAttrib not implemented
04-08 18:53:54.760 3299-3328/ayalma.ir.myapplication W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe2e1cb00, error=EGL_SUCCESS
04-08 18:53:56.200 3299-3299/ayalma.ir.myapplication I/art: Rejecting re-init on previously-failed class java.lang.Class<carbon.drawable.EdgeEffectCompat>
04-08 18:53:56.200 3299-3299/ayalma.ir.myapplication E/InputEventReceiver: Exception dispatching input event.
04-08 18:53:56.200 3299-3299/ayalma.ir.myapplication E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
04-08 18:53:56.200 3299-3299/ayalma.ir.myapplication E/MessageQueue-JNI: java.lang.IncompatibleClassChangeError: carbon.drawable.EdgeEffectCompat
                                                                             at carbon.widget.RecyclerView.ensureTopGlow(RecyclerView.java:151)
                                                                             at carbon.widget.RecyclerView.dispatchTouchEvent(RecyclerView.java:198)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at carbon.widget.ViewPager.dispatchTouchEvent(ViewPager.java:219)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at carbon.beta.CoordinatorLayout.dispatchTouchEvent(CoordinatorLayout.java:283)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at carbon.widget.DrawerLayout.dispatchTouchEvent(DrawerLayout.java:281)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                             at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                             at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                             at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                             at android.app.Activity.dispatchTouchEvent(Activity.java:2765)
                                                                             at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                             at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                             at android.view.View.dispatchPointerEvent(View.java:9514)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                             at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                             at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                             at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                             at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                             at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                             at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                             at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                             at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                             at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                             at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
                                                                             at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                             at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                             at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                             at android.os.Looper.loop(Looper.java:135)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteI
04-08 18:53:56.200 3299-3299/ayalma.ir.myapplication D/AndroidRuntime: Shutting down VM
04-08 18:53:56.200 3299-3299/ayalma.ir.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: ayalma.ir.myapplication, PID: 3299
                                                                       java.lang.IncompatibleClassChangeError: carbon.drawable.EdgeEffectCompat
                                                                           at carbon.widget.RecyclerView.ensureTopGlow(RecyclerView.java:151)
                                                                           at carbon.widget.RecyclerView.dispatchTouchEvent(RecyclerView.java:198)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at carbon.widget.ViewPager.dispatchTouchEvent(ViewPager.java:219)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at carbon.beta.CoordinatorLayout.dispatchTouchEvent(CoordinatorLayout.java:283)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at carbon.widget.DrawerLayout.dispatchTouchEvent(DrawerLayout.java:281)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2553)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2197)
                                                                           at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2403)
                                                                           at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1737)
                                                                           at android.app.Activity.dispatchTouchEvent(Activity.java:2765)
                                                                           at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
                                                                           at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2364)
                                                                           at android.view.View.dispatchPointerEvent(View.java:9514)
                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
                                                                           at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                           at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                           at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                           at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                           at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                           at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                           at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                           at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
                                                                           at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
                                                                           at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
                                                                           at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
                                                                           at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                           at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                           at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteIn
04-08 18:54:58.720 3299-3299/? I/Process: Sending signal. PID: 3299 SIG: 9
```

**Comment by ZieIony** [comment]
```
java.lang.IncompatibleClassChangeError: carbon.drawable.EdgeEffectCompat
```

EdgeEffectCompat has changed between versions of Google libraries. You're using different version than Carbon does. It's connected to support RecyclerView library.

**Comment by ayalma** [comment]
yes you are right . 
i removed v4 library and everything working good.
but in my debugging process i found that google make EdgeEffectCompat final in last version of v4 support and   carbon can't inherit from EdgeEffectCompat. in my opinion this is a real problem.

**Comment by ZieIony** [comment]
Yup, that's the real problem. There's nothing much I can do about it. I've copied EdgeEffect from Android sources for my internal use, but it conflicts when two different RecyclerViews are used (one with old EdgeEffect and one with the new final one).
