### ISSUE TITLE
Error inflating class carbon.widget.EditText 

### ISSUE THREAD

**Issue by katharineE** [ZieIony/Carbon#240]
When inflating a carbon.widget.EditText, I get an exception: android.view.InflateException: Binary XML file line #2:  Error inflating class carbon.widget.EditText. Any help would be awesome! Thanks

The following is my EditText code: 

```
<?xml version="1.0" encoding="utf-8"?>
<carbon.widget.EditText
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:id="@+id/tools_free_text_edittext"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:hint="test"
    app:carbon_floatingLabel="false"/>
```

This is how I inflate the EditText:

```
LayoutInflater inflater = (LayoutInflater) mPDFView.getContext().getSystemService(Context.LAYOUT_INFLATER_SERVICE);
View editView = inflater.inflate(R.layout.tools_free_text_inline_edittext, null, false);
```

And this is the full stack trace:

```
android.view.InflateException: Binary XML file line #2: Error inflating class carbon.widget.EditText
at android.view.LayoutInflater.createView(LayoutInflater.java:640)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
at com.pdftron.pdf.utils.InlineEditText.<init>(InlineEditText.java:56)
at com.pdftron.pdf.tools.FreeTextCreate.createFreeText(FreeTextCreate.java:378)
at com.pdftron.pdf.tools.FreeTextCreate.initFreeText(FreeTextCreate.java:316)
at com.pdftron.pdf.tools.Pan.onQuickMenuClicked(Pan.java:408)
at com.pdftron.pdf.tools.Tool$1.onDismiss(Tool.java:1027)
at android.widget.PopupWindow.dismiss(PopupWindow.java:1542)
at com.pdftron.pdf.tools.QuickMenu.dismiss(QuickMenu.java:1206)
at com.pdftron.pdf.tools.QuickMenu$MenuView.onTouchEvent(QuickMenu.java:552)
at android.view.View.dispatchTouchEvent(View.java:8975)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
at android.widget.PopupWindow$PopupViewContainer.dispatchTouchEvent(PopupWindow.java:1937)
at android.view.View.dispatchPointerEvent(View.java:9180)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4741)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4579)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4107)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4160)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4126)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4236)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4134)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4293)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4107)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4160)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4126)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4134)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4107)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6610)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6494)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6465)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6700)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:143)
at android.os.Looper.loop(Looper.java:130)
at android.app.ActivityThread.main(ActivityThread.java:5981)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

Caused by: java.lang.reflect.InvocationTargetException
at android.view.LayoutInflater.createView(LayoutInflater.java:614)
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:483) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
at com.pdftron.pdf.utils.InlineEditText.<init>(InlineEditText.java:56) 
at com.pdftron.pdf.tools.FreeTextCreate.createFreeText(FreeTextCreate.java:378) 
at com.pdftron.pdf.tools.FreeTextCreate.initFreeText(FreeTextCreate.java:316) 
at com.pdftron.pdf.tools.Pan.onQuickMenuClicked(Pan.java:408) 
at com.pdftron.pdf.tools.Tool$1.onDismiss(Tool.java:1027) 
at android.widget.PopupWindow.dismiss(PopupWindow.java:1542) 
at com.pdftron.pdf.tools.QuickMenu.dismiss(QuickMenu.java:1206) 
at com.pdftron.pdf.tools.QuickMenu$MenuView.onTouchEvent(QuickMenu.java:552) 
at android.view.View.dispatchTouchEvent(View.java:8975) 
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709) 
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425) 
at android.widget.PopupWindow$PopupViewContainer.dispatchTouchEvent(PopupWindow.java:1937) 
at android.view.View.dispatchPointerEvent(View.java:9180) 
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4741) 
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4579) 
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4107) 
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4160) 
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4126) 
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4236) 
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4134) 
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4293) 
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4107) 
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4160) 
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4126) 
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4134) 
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4107) 
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6610) 
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6494) 
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6465) 
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6700) 
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185) 
at android.os.MessageQueue.nativePollOnce(Native Method) 
at android.os.MessageQueue.next(MessageQueue.java:143) 
at android.os.Looper.loop(Looper.java:130) 
at android.app.ActivityThread.main(ActivityThread.java:5981) 
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:372) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194) 

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.content.res.ColorStateList.getDefaultColor()' on a null object reference
at carbon.widget.EditText.initEditText(EditText.java:221)
at carbon.widget.EditText.<init>(EditText.java:152)
at java.lang.reflect.Constructor.newInstance(Native Method) 
at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
at android.view.LayoutInflater.createView(LayoutInflater.java:614) 
at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:483) 
at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
at com.pdftron.pdf.utils.InlineEditText.<init>(InlineEditText.java:56) 
at com.pdftron.pdf.tools.FreeTextCreate.createFreeText(FreeTextCreate.java:378) 
at com.pdftron.pdf.tools.FreeTextCreate.initFreeText(FreeTextCreate.java:316) 
at com.pdftron.pdf.tools.Pan.onQuickMenuClicked(Pan.java:408) 
at com.pdftron.pdf.tools.Tool$1.onDismiss(Tool.java:1027) 
at android.widget.PopupWindow.dismiss(PopupWindow.java:1542) 
at com.pdftron.pdf.tools.QuickMenu.dismiss(QuickMenu.java:1206) 
at com.pdftron.pdf.tools.QuickMenu$MenuView.onTouchEvent(QuickMenu.java:552) 
at android.view.View.dispatchTouchEvent(View.java:8975) 
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709) 
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425) 
at android.widget.PopupWindow$PopupViewContainer.dispatchTouchEvent(PopupWindow.java:1937) 
at android.view.View.dispatchPointerEvent(View.java:9180) 
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4741) 
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4579) 
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4107) 
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4160) 
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4126) 
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4236) 
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4134) 
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4293) 
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4107) 
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4160) 
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4126) 
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4134) 
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4107) 
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6610) 
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6494) 
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6465) 
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6700) 
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185) 
at android.os.MessageQueue.nativePollOnce(Native Method) 
at android.os.MessageQueue.next(MessageQueue.java:143) 
at android.os.Looper.loop(Looper.java:130) 
at android.app.ActivityThread.main(ActivityThread.java:5981) 
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:372) 
android.view.InflateException: Binary XML file line #2: Error inflating class carbon.widget.EditText
```

**Comment by ZieIony** [comment]
1. Which version are you using?
2. Did you complete all installation steps as described here: https://github.com/ZieIony/Carbon/wiki/Installation ?
3. Is it working when inflating a simple layout by calling setContentView(resId) in an Activity?

**Comment by katharineE** [comment]
Thanks for the speedy reply!
1.  0.13.0
2.  I did completed those installation steps. I added this line to my dependencies:

`compile 'tk.zielony:carbon:0.13.0'`

And these lines to my defaultConfig:

```
renderscriptTargetApi 20
renderscriptSupportModeEnabled true
```

However adding the above lines to defaultConfig caused a couple DuplicateFileException for files in the build folder, so I added this to my packagingOptions:

```
exclude 'lib/armeabi-v7a/libblasV8.so'
exclude 'lib/armeabi-v7a/libRSSupport.so'
exclude 'lib/armeabi-v7a/librsjni.so'
exclude 'lib/mips/libRSSupport.so'
exclude 'lib/mips/libblasV8.so'
exclude 'lib/mips/librsjni.so'
exclude 'lib/x86/libRSSupport.so'
exclude 'lib/x86/libblasV8.so'
exclude 'lib/x86/librsjni.so'
```
1.  I used setContentView(resId) in an Activity, using the same layout as the EditText above and it also crashes with the same null ptr exception as above.

**Comment by ZieIony** [comment]
4 . You should be using one of Carbon's themes.

That line (_carbon.widget.EditText.initEditText(EditText.java:221)_) sets tint color. Tint should always be non-null. I'll double check if there's a way to pass a null value to tint.

**Comment by katharineE** [comment]
Sorry! I forgot. 
4. I also changed the app theme to a Carbon theme using:
`<style name="AppTheme" parent="carbon_Theme.Light.NoActionBar">`

However, it is still crashing with the same null pointer exception regarding the tint color. Is there a way to manually set the tint? I've tried setting tint variables within the EditText, but that isn't working:

```
android:backgroundTint="@color/white"
android:drawableTint="@color/white"
android:foregroundTint="@color/white"
```

Thanks!

**Comment by katharineE** [comment]
Hey, I realized I was not setting the theme of the activity correctly. I tested setting the theme in just the EditText itself and it worked. Thanks for your help!
(I tested it by adding this line to my editText: 

```
app:theme="@style/carbon_EditText"
```

)
