### ISSUE TITLE
Sample app crash when opening CheckBox sample

### ISSUE THREAD

**Issue by wasdennnoch** [ZieIony/Carbon#247]
Title says it. Android 6.0.1 (RR), latest sample app as of now.

Stack trace:

``````
java.lang.RuntimeException: Unable to start activity ComponentInfo{tk.zielony.carbonsamples/tk.zielony.carbonsamples.widget.CheckBoxRadioActivity}: android.view.InflateException: Binary XML file line #12: Binary XML file line #12: Error inflating class carbon.widget.ScrollView
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2462)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5471)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
Caused by: android.view.InflateException: Binary XML file line #12: Binary XML file line #12: Error inflating class carbon.widget.ScrollView
    at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
    at android.view.LayoutInflater.inflate(<Xposed>)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
    at android.view.LayoutInflater.inflate(<Xposed>)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
    at android.view.LayoutInflater.inflate(<Xposed>)
    at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:449)
    at android.app.Activity.setContentView(Activity.java:2437)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
    at android.app.Activity.setContentView(<Xposed>)
    at tk.zielony.carbonsamples.widget.CheckBoxRadioActivity.onCreate(CheckBoxRadioActivity.java:18)
    at android.app.Activity.performCreate(Activity.java:7125)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2415)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5471)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
Caused by: android.view.InflateException: Binary XML file line #12: Error inflating class carbon.widget.ScrollView
    at android.view.LayoutInflater.createView(LayoutInflater.java:645)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
    at android.view.LayoutInflater.inflate(<Xposed>)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
    at android.view.LayoutInflater.inflate(<Xposed>)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
    at android.view.LayoutInflater.inflate(<Xposed>)
    at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:449)
    at android.app.Activity.setContentView(Activity.java:2437)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
    at android.app.Activity.setContentView(<Xposed>)
    at tk.zielony.carbonsamples.widget.CheckBoxRadioActivity.onCreate(CheckBoxRadioActivity.java:18)
    at android.app.Activity.performCreate(Activity.java:7125)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2415)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5471)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
Caused by: java.lang.reflect.InvocationTargetException
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at android.view.LayoutInflater.createView(LayoutInflater.java:619)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
    at android.view.LayoutInflater.inflate(<Xposed>)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
    at android.view.LayoutInflater.inflate(<Xposed>)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
    at android.view.LayoutInflater.inflate(<Xposed>)
    at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:449)
    at android.app.Activity.setContentView(Activity.java:2437)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
    at android.app.Activity.setContentView(<Xposed>)
    at tk.zielony.carbonsamples.widget.CheckBoxRadioActivity.onCreate(CheckBoxRadioActivity.java:18)
    at android.app.Activity.performCreate(Activity.java:7125)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2415)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5471)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
    at carbon.widget.ScrollView.initScrollbars(ScrollView.java:402)
    at carbon.widget.ScrollView.initScrollView(ScrollView.java:99)
    at carbon.widget.ScrollView.<init>(ScrollView.java:60)
    at java.lang.reflect.Constructor.newInstance(Native Method)
    at android.view.LayoutInflater.createView(LayoutInflater.java:619)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
    at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
    at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
    at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
    at android.view.LayoutInflater.inflate(<Xposed>)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
    at android.view.LayoutInflater.inflate(<Xposed>)
    at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
    at android.view.LayoutInflater.inflate(<Xposed>)
    at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:449)
    at android.app.Activity.setContentView(Activity.java:2437)
    at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
    at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
    at android.app.Activity.setContentView(<Xposed>)
    at tk.zielony.carbonsamples.widget.CheckBoxRadioActivity.onCreate(CheckBoxRadioActivity.java:18)
    at android.app.Activity.performCreate(Activity.java:7125)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2415)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2522)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5471)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)```
``````

**Comment by wasdennnoch** [comment]
Same thing with the buttons sample.

**Comment by ZieIony** [comment]
fixed
