### ISSUE TITLE
Carbon EditText causes force close on deselecting text

### ISSUE THREAD

**Issue by ompcj4u** [ZieIony/Carbon#266]
I'm using Carbon Edittext in an android application with custom style. When I tap on the text inside edittext, all text will be highlited and a menu (containing cut, copy, paste and select all) appears on top of screen. But when I deselect the text (by clicking on other EditTexts or choosing one of menu items) it causes app to be closed (force close) with bellow error.

`java.lang.NullPointerException
                                                                           at carbon.widget.EditText$5.onDestroyActionMode(EditText.java:757)
                                                                           at com.android.internal.policy.impl.PhoneWindow$DecorView$ActionModeCallbackWrapper.onDestroyActionMode(PhoneWindow.java:3260)
                                                                           at com.android.internal.view.StandaloneActionMode.finish(StandaloneActionMode.java:104)
                                                                           at android.widget.Editor.stopSelectionActionMode(Editor.java:2027)
                                                                           at android.widget.Editor.hideCursorControllers(Editor.java:696)
                                                                           at android.widget.Editor.hideControllers(Editor.java:680)
                                                                           at android.widget.Editor.onTouchUpEvent(Editor.java:1989)
                                                                           at android.widget.TextView.onTouchEvent(TextView.java:8624)
                                                                           at carbon.widget.EditText.onTouchEvent(EditText.java:1067)
                                                                           at android.view.View.dispatchTouchEvent(View.java:7669)
                                                                           at carbon.widget.EditText.dispatchTouchEvent(EditText.java:1074)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2397)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2397)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2397)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2397)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2397)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
                                                                           at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2397)
                                                                           at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2134)
                                                                           at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2283)
                                                                           at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1578)
                                                                           at android.app.Dialog.dispatchTouchEvent(Dialog.java:767)
                                                                           at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2231)
                                                                           at android.view.View.dispatchPointerEvent(View.java:7876)
                                                                           at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3898)
                                                                           at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3782)
                                                                           at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5034)
                                                                           at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5013)
                                                                           at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5112)
                                                                           at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
                                                                           at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                           at android.os.MessageQueue.next(MessageQueue.java:125)
                                                                           at android.os.Looper.loop(Looper.java:124)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5279)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:511)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
                                                                           at dalvik.system.NativeStart.main(Native Method)`

**this is how EditText is initialized :**

```
<android.support.design.widget.TextInputLayout
                    android:id="@+id/lblMaximetre"
                    android:layout_width="0dp"
                    android:layout_height="wrap_content"
                    android:layout_margin="5dp"
                    android:visibility="gone"
                    android:layout_weight="0.33"
                    app:hintTextAppearance="@style/TextLabel">

                    <carbon.widget.EditText
                        android:id="@+id/txtMaximetre"
                        android:layout_width="match_parent"
                        android:layout_height="wrap_content"
                        android:gravity="right"
                        android:hint="aaaa"
                        android:inputType="numberDecimal"
                        android:imeOptions="actionNext"
                        android:maxLength="9"
                        android:maxLines="1"
                        android:singleLine="true" />
                </android.support.design.widget.TextInputLayout>
```

**And this is how I added style to my project**

```
<style name="AppTheme" parent="carbon_Theme.Light.NoActionBar">
        <item name="android:windowTranslucentStatus">true</item>
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorDarkPrimary</item>
        <item name="colorAccent">@color/colorAccent</item>s
        <item name="android:windowFullscreen">true</item>
        <item name="carbon_colorError">@color/carbon_amber_400</item>
        <item name="drawerArrowStyle">@style/MyDrawerArrowToggle</item>
        <item name="android:textViewStyle">@style/MyTextViewStyleMediumNormal</item>
        <item name="android:editTextStyle">@style/MyEditTextStyleMediumNormal</item>
        <item name="android:buttonStyle">@style/btnStyle</item>
        <item name="carbon_fontPath">fonts/IRANSans.ttf</item>
    </style>

    <style name="MyEditTextStyleMediumNormal" parent="carbon_EditText">
        <item name="carbon_fontPath">fonts/myFont.ttf</item>
        <item name="android:textSize">15sp</item>
        <item name="android:textColor">@color/carbon_grey_700</item>
    </style>

```

How can solve this issue ?
I didn't have this problem in other projects, but couldn't get rid of this issue in new project.
I don't face this problem when replacing **carbon.widget.EditText** with **EditText**.

**Comment by ZieIony** [comment]
I suppose that you're using an old version of Carbon, as this issue was spotted long time ago and the current EditText implementation doesn't have that fancy menu. The implementation you're using was moved to carbon.beta package as MarshmallowEditText. I would recommend to update Carbon to the most recent version or stop using EditText of your version as there's a known issue with it.

**Comment by ompcj4u** [comment]
What is the last version ? I'm currently using the **version '0.13.0'**
How can I be aware of the last version?
Thank you for your support

**Comment by ZieIony** [comment]
The most recent version is 0.14.0. This build is very different, so you may experience some issues with deprecated and changed classes.

Usually I update the readme page, the installation page, the G+ community and Carbon's Maven repository. The most recent build is fresh and I had no time to do that yet.

Community: https://plus.google.com/u/1/communities/111973718340428039040
