### ISSUE TITLE
AutoCompleteEditText crash

### ISSUE THREAD

**Issue by ZieIony** [ZieIony/Carbon#270]
java.lang.StackOverflowError
                                                                            at android.text.DynamicLayout.reflow(DynamicLayout.java:332)
                                                                            at android.text.DynamicLayout.access$000(DynamicLayout.java:41)
                                                                            at android.text.DynamicLayout$ChangeWatcher.reflow(DynamicLayout.java:686)
                                                                            at android.text.DynamicLayout$ChangeWatcher.onTextChanged(DynamicLayout.java:696)
                                                                            at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:962)
                                                                            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:496)
                                                                            at android.text.SpannableStringBuilder.insert(SpannableStringBuilder.java:207)
                                                                            at android.text.SpannableStringBuilder.insert(SpannableStringBuilder.java:30)
                                                                            at carbon.widget.AutoCompleteEditText.autoComplete(AutoCompleteEditText.java:198)
                                                                            at carbon.widget.AutoCompleteEditText.access$100(AutoCompleteEditText.java:30)
                                                                            at carbon.widget.AutoCompleteEditText$1.afterTextChanged(AutoCompleteEditText.java:136)
                                                                            at android.widget.TextView.sendAfterTextChanged(TextView.java:7426)
                                                                            at android.widget.TextView$ChangeWatcher.afterTextChanged(TextView.java:9229)
                                                                            at android.text.SpannableStringBuilder.sendAfterTextChanged(SpannableStringBuilder.java:970)
                                                                            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:497)
                                                                            at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:212)
                                                                            at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:30)
                                                                            at carbon.widget.AutoCompleteEditText.autoComplete(AutoCompleteEditText.java:182)
                                                                            at carbon.widget.AutoCompleteEditText.onSelectionChanged(AutoCompleteEditText.java:294)
                                                                            at android.widget.TextView.spanChange(TextView.java:7518)
                                                                            at android.widget.TextView$ChangeWatcher.onSpanChanged(TextView.java:9239)
                                                                            at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:999)
                                                                            at android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuilder.java:567)
                                                                            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:500)
                                                                            at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:212)
                                                                            at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:30)
                                                                            at carbon.widget.AutoCompleteEditText.autoComplete(AutoCompleteEditText.java:182)
                                                                            at carbon.widget.AutoCompleteEditText.onSelectionChanged(AutoCompleteEditText.java:294)
                                                                            at android.widget.TextView.spanChange(TextView.java:7518)
                                                                            at android.widget.TextView$ChangeWatcher.onSpanChanged(TextView.java:9239)
                                                                            at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:999)
                                                                            at android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuilder.java:567)
                                                                            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:500)
                                                                            at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:212)
                                                                            at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:30)
                                                                            at carbon.widget.AutoCompleteEditText.autoComplete(AutoCompleteEditText.java:182)
                                                                            at carbon.widget.AutoCompleteEditText.onSelectionChanged(AutoCompleteEditText.java:294)
                                                                            at android.widget.TextView.spanChange(TextView.java:7518)
                                                                            at android.widget.TextView$ChangeWatcher.onSpanChanged(TextView.java:9239)
                                                                            at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:999)
                                                                            at android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuilder.java:567)
                                                                            at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:500)
                                                                            at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:212)
                                                                            at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:30)
                                                                            at carbon.widget.AutoCompleteEditText.autoComplete(AutoCompleteEditText.java:182)
                                                                            at carbon.widget.AutoCompleteEditText.onSelectionChanged(AutoCompleteEditText.java:294)
                                                                            at android.widget.TextView.spanChange(TextView.java:7518)
                                                                            at android.widget.TextView$ChangeWatcher.onSpanChanged(TextView.java:9239)
                                                                            at android.text.SpannableStringBuilder.sendSpanChanged(SpannableStringBuilder.java:999)
                                                                        	at android.text.SpannableStringBuilder.sendToSpanWatchers(SpannableStringBuild

**Comment by ZieIony** [comment]
fixed
