### ISSUE TITLE
Floating action menu dose not hide.

### ISSUE THREAD

**Issue by galibimtiaz** [ZieIony/Carbon#288]
Have been trying to hide single floating action menu but its not working, not programmatically nor from xml.

**Comment by ZieIony** [comment]
What do you mean by single? Does it work in other cases?

**Comment by galibimtiaz** [comment]
No What I meant I just tried to hide a single one from a group of menus , didn't tried other cases , I should't have write that.

**Comment by galibimtiaz** [comment]
Ok just tried to hide them one by one and by the whole group, none of them work.

**Comment by ZieIony** [comment]
Carbon doesn't really use MenuItem objects internally. It's just a hack to make it possible to load menus from xml. If you're using MenuItem's methods, it won't work.

I didn't spend much time on FAB menu, because nobody ever needed that. I don't know if it would be possible to make MenuItem's methods work. Let me keep this issue open, so I can check that.

**Comment by ZieIony** [comment]
Done. Check Widgets/FloatingActionMenu sample for details.

**Comment by galibimtiaz** [comment]
```
 E/UncaughtException: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.animation.Animator.addListener(android.animation.Animator$AnimatorListener)' on a null object reference
                                                                                       at carbon.widget.FloatingActionMenu.dismiss(FloatingActionMenu.java:108)
                                                                                       at carbon.widget.FloatingMenuItem.lambda$build$0(FloatingMenuItem.java:74)
                                                                                       at carbon.widget.FloatingMenuItem$$Lambda$1.onClick(Unknown Source)
                                                                                       at android.view.View.performClick(View.java:5646)
                                                                                       at android.view.View$PerformClick.run(View.java:22450)
                                                                                       at android.os.Handler.handleCallback(Handler.java:755)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                       at android.os.Looper.loop(Looper.java:156)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
04-20 12:30:47.317 12455-12455/com.twiined.galib.pushlocation E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.twiined.galib.pushlocation, PID: 12455
                                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'void android.animation.Animator.addListener(android.animation.Animator$AnimatorListener)' on a null object reference
                                                                                    at carbon.widget.FloatingActionMenu.dismiss(FloatingActionMenu.java:108)
                                                                                    at carbon.widget.FloatingMenuItem.lambda$build$0(FloatingMenuItem.java:74)
                                                                                    at carbon.widget.FloatingMenuItem$$Lambda$1.onClick(Unknown Source)
                                                                                    at android.view.View.performClick(View.java:5646)
                                                                                    at android.view.View$PerformClick.run(View.java:22450)
                                                                                    at android.os.Handler.handleCallback(Handler.java:755)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:156)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```


Keep getting this error when even I press a menu button.

**Comment by galibimtiaz** [comment]
Seems like I don't need to choose a menu as well , when ever I press the fab again to hide the popup window of menus it crushes.

**Comment by ZieIony** [comment]
Moved to #289
