### ISSUE TITLE
Clicking on FloatingActionMenu causes NPE

### ISSUE THREAD

**Issue by ZieIony** [ZieIony/Carbon#289]
Separated from #288

```
 E/UncaughtException: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.animation.Animator.addListener(android.animation.Animator$AnimatorListener)' on a null object reference
                                                                                       at carbon.widget.FloatingActionMenu.dismiss(FloatingActionMenu.java:108)
                                                                                       at carbon.widget.FloatingMenuItem.lambda$build$0(FloatingMenuItem.java:74)
                                                                                       at carbon.widget.FloatingMenuItem$$Lambda$1.onClick(Unknown Source)
                                                                                       at android.view.View.performClick(View.java:5646)
                                                                                       at android.view.View$PerformClick.run(View.java:22450)
                                                                                       at android.os.Handler.handleCallback(Handler.java:755)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                       at android.os.Looper.loop(Looper.java:156)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
04-20 12:30:47.317 12455-12455/com.twiined.galib.pushlocation E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                Process: com.twiined.galib.pushlocation, PID: 12455
                                                                                java.lang.NullPointerException: Attempt to invoke virtual method 'void android.animation.Animator.addListener(android.animation.Animator$AnimatorListener)' on a null object reference
                                                                                    at carbon.widget.FloatingActionMenu.dismiss(FloatingActionMenu.java:108)
                                                                                    at carbon.widget.FloatingMenuItem.lambda$build$0(FloatingMenuItem.java:74)
                                                                                    at carbon.widget.FloatingMenuItem$$Lambda$1.onClick(Unknown Source)
                                                                                    at android.view.View.performClick(View.java:5646)
                                                                                    at android.view.View$PerformClick.run(View.java:22450)
                                                                                    at android.os.Handler.handleCallback(Handler.java:755)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                    at android.os.Looper.loop(Looper.java:156)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:6524)
                                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
```

"Keep getting this error when even I press a menu button."

**Comment by ZieIony** [comment]
"Seems like I don't need to choose a menu as well , when ever I press the fab again to hide the popup window of menus it crushes."

**Comment by ZieIony** [comment]
should be fine now
