### ISSUE TITLE
java.lang.IndexOutOfBoundsException

### ISSUE THREAD

**Issue by reaper12** [ZieIony/Carbon#298]
Device:Google Pixel

Android:7.1.1

xml:

```
<carbon.widget.LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:fitsSystemWindows="true"
    android:orientation="vertical"
    app:carbon_insetColor="?attr/colorPrimary">

    <VideoView
        android:layout_width="match_parent"
        android:layout_height="match_parent"/>

</carbon.widget.LinearLayout>
```
Erorr:
```
 java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
                                                     at java.util.ArrayList.get(ArrayList.java:411)
                                                     at carbon.widget.LinearLayout.getChildDrawingOrder(LinearLayout.java:266)
                                                     at android.view.ViewGroup.getAndVerifyPreorderedIndex(ViewGroup.java:1733)
                                                     at android.view.ViewGroup.buildOrderedChildList(ViewGroup.java:3645)
                                                     at android.view.ViewGroup.gatherTransparentRegion(ViewGroup.java:6380)
                                                     at android.view.ViewGroup.gatherTransparentRegion(ViewGroup.java:6388)
                                                     at android.view.ViewGroup.gatherTransparentRegion(ViewGroup.java:6388)
                                                     at android.view.ViewGroup.gatherTransparentRegion(ViewGroup.java:6388)
                                                     at android.view.ViewGroup.gatherTransparentRegion(ViewGroup.java:6388)
                                                     at android.view.ViewGroup.gatherTransparentRegion(ViewGroup.java:6388)
                                                     at com.android.internal.policy.DecorView.gatherTransparentRegion(DecorView.java:270)
                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2081)
                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1254)
                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6337)
                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:874)
                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:686)
                                                     at android.view.Choreographer.doFrame(Choreographer.java:621)
                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:860)
                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                     at android.os.Looper.loop(Looper.java:154)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by reaper12** [comment]
Hi! If you don't have this phone, you can add genymotion device:Google Pixel -7.1.0-API 25- 1080x1920  to test.

**Comment by ZieIony** [comment]
Thank you for the report. This issue doesn't happen on any device I have. The bugfix is very simple, I'll try to commit it today.

**Comment by ZieIony** [comment]
fixed
