### ISSUE TITLE
Sometimes crash when click some items

### ISSUE THREAD

**Issue by wheat7** [ZieIony/Carbon#306]
In this version, sometimes crash when click some items , test phone is Samsung s6 edge and XiaoMI Mi6

**Comment by ZieIony** [comment]
Could you please list these items? If you have access to logs, please add them as well.

**Comment by wheat7** [comment]
For example item ToolBar.
Log:
07-10 17:51:49.741 21085-21085/tk.zielony.carbonsamples E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: tk.zielony.carbonsamples, PID: 21085
                                                                          java.lang.RuntimeException: Unable to start activity ComponentInfo{tk.zielony.carbonsamples/tk.zielony.carbonsamples.widget.ToolbarActivity}: android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class carbon.widget.EditText
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                                              at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:158)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:7237)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                           Caused by: android.view.InflateException: Binary XML file line #15: Binary XML file line #15: Error inflating class carbon.widget.EditText
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:551)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:429)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:380)
                                                                              at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                              at tk.zielony.carbonsamples.widget.ToolbarActivity.onCreate(ToolbarActivity.java:15)
                                                                              at android.app.Activity.performCreate(Activity.java:6876)
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                              at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:158) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                           Caused by: android.view.InflateException: Binary XML file line #15: Error inflating class carbon.widget.EditText
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:657)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:847)
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:855)
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:527)
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                              at tk.zielony.carbonsamples.widget.ToolbarActivity.onCreate(ToolbarActivity.java:15) 
                                                                              at android.app.Activity.performCreate(Activity.java:6876) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                              at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:158) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                           Caused by: java.lang.reflect.InvocationTargetException
                                                                              at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:631)
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                              at tk.zielony.carbonsamples.widget.ToolbarActivity.onCreate(ToolbarActivity.java:15) 
                                                                              at android.app.Activity.performCreate(Activity.java:6876) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                              at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:158) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
                                                                           Caused by: java.lang.RuntimeException: Cannot make calls to a recycled instance!
                                                                              at android.content.res.TypedArray.getValue(TypedArray.java:930)
                                                                              at carbon.widget.EditText.initEditText(EditText.java:191)
                                                                              at carbon.widget.EditText.<init>(EditText.java:102)
                                                                              at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                              at android.view.LayoutInflater.createView(LayoutInflater.java:631) 
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776) 
                                                                              at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:716) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:847) 
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                              at android.view.LayoutInflater.rInflate(LayoutInflater.java:855) 
                                                                              at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:810) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:527) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:429) 
                                                                              at android.view.LayoutInflater.inflate(LayoutInflater.java:380) 
                                                                              at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
                                                                              at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                              at tk.zielony.carbonsamples.widget.ToolbarActivity.onCreate(ToolbarActivity.java:15) 
                                                                              at android.app.Activity.performCreate(Activity.java:6876) 
                                                                              at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
                                                                              at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207) 
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                              at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                              at android.os.Looper.loop(Looper.java:158) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:7237) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by wheat7** [comment]
PS:Android studio version is 3.0 Preview and Gradle is 3.0 alpha5

**Comment by ZieIony** [comment]
Thanks! Recent Samsung devices have more strict tests than my phone, so I didn't notice that bug.

**Comment by wheatdamon** [comment]
Ok,Thank you for your work! Carbon is the best Material Design library in my heart.

**Comment by wheat7** [comment]
Ok,Thank you for your work! Carbon is the best Material Design library in my heart.

**Comment by ZieIony** [comment]
Cool.

The fix is on dev branch.

**Comment by wheat7** [comment]
Cool,I've tried

**Comment by wheat7** [comment]
Cool,I've tried.

**Comment by ZieIony** [comment]
Most of the users prefer stable Maven releases. I'm glad that there are guy like you, who check the repository code from time to time. It helps me a lot with bugs like this one. And it's good to know, that my work is still useful to someone :)
