### ISSUE TITLE
Support Library Vector Drawables not working

### ISSUE THREAD

**Issue by hectorgabucio** [ZieIony/Carbon#307]
The problem is that I can't use vector drawables support for older API's. It is easy to reproduce, this is the code:

    <carbon.widget.FloatingActionButton
        style="@style/carbon_FloatingActionButton"
        android:layout_width="@dimen/carbon_fabSize"
        android:layout_height="@dimen/carbon_fabSize"
        android:layout_margin="@dimen/carbon_padding"
        android:padding="@dimen/carbon_padding"
        android:scaleType="fitXY"
        app:srcCompat="@drawable/ic_directions_walk_black_24dp"
        android:tag="enable"/>

The vector won't show. In the other hand, if I change "carbon.widget.FloatingActionButton" to "android.support.design.widget.FloatingActionButton", it will show. So my project is well configured to support vector drawables.

I attach a sample project that demonstrates this issue:
https://drive.google.com/file/d/0B7-yT1Ci-C14SVNQX1pfd1REZUk/view?usp=sharing

Tested in:
- Motorola Moto G4 Plus, Android 7.0
- Galaxy Core 2 SM-G355HN, Android 4.4.4

**Comment by ZieIony** [comment]
I'm getting exactly the same exception in both cases

```Java
Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f070058
    at android.content.res.Resources.getValue(Resources.java:1026)
    at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:332)
    at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
    at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
    at android.support.v7.widget.AppCompatDrawableManager.checkVectorDrawableSetup(AppCompatDrawableManager.java:711)
    at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:195)
    at android.support.v7.widget.TintTypedArray.getDrawableIfKnown(TintTypedArray.java:81)
    at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:131)
    at android.support.v7.app.AppCompatDelegateImplV9.<init>(AppCompatDelegateImplV9.java:155)
    at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:31)
    at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:55)
    at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:205)
    at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:185)
    at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:519)
    at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:71)
    at trainer.hector.myapplication.MainActivity.onCreate(MainActivity.java:10)
    at android.app.Activity.performCreate(Activity.java:5047)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2056)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2117) 
    at android.app.ActivityThread.access$700(ActivityThread.java:134) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1218) 
    at android.os.Handler.dispatchMessage(Handler.java:99) 
    at android.os.Looper.loop(Looper.java:137) 
    at android.app.ActivityThread.main(ActivityThread.java:4867) 
    at java.lang.reflect.Method.invokeNative(Native Method) 
    at java.lang.reflect.Method.invoke(Method.java:511) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1007) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:774) 
    at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by ZieIony** [comment]
0.14.0 does not support Support Library Vector Drawables from xml. 0.15.0 will, but it's not released yet. If you wish, you can clone the repo, or use JitPack and try a nightly build.
