### ISSUE TITLE
Rendering issue on carbon.widget.button caused by SVG drawable on drawableTop/Bottom/Left/Right.

### ISSUE THREAD

**Issue by Andrei-Stakov** [ZieIony/Carbon#321]
Here's the error log:

```
java.awt.image.RasterFormatException: (x + width) is outside raster
	at sun.awt.image.IntegerInterleavedRaster.createWritableChild(IntegerInterleavedRaster.java:467)
	at sun.awt.image.IntegerInterleavedRaster.createChild(IntegerInterleavedRaster.java:514)
	at sun.java2d.pipe.GeneralCompositePipe.renderPathTile(GeneralCompositePipe.java:106)
	at sun.java2d.pipe.AAShapePipe.renderTiles(AAShapePipe.java:201)
	at sun.java2d.pipe.AAShapePipe.fillParallelogram(AAShapePipe.java:102)
	at sun.java2d.pipe.PixelToParallelogramConverter.fillRectangle(PixelToParallelogramConverter.java:322)
	at sun.java2d.pipe.PixelToParallelogramConverter.fillRect(PixelToParallelogramConverter.java:115)
	at sun.java2d.pipe.ValidatePipe.fillRect(ValidatePipe.java:76)
	at sun.java2d.SunGraphics2D.fillRect(SunGraphics2D.java:2421)
	at android.graphics.PorterDuffColorFilter_Delegate.applyFilter(PorterDuffColorFilter_Delegate.java:71)
	at com.android.layoutlib.bridge.impl.GcSnapshot.drawInLayer(GcSnapshot.java:665)
	at com.android.layoutlib.bridge.impl.GcSnapshot.draw(GcSnapshot.java:585)
	at android.graphics.BaseCanvas_Delegate.draw(BaseCanvas_Delegate.java:555)
	at android.graphics.BaseCanvas_Delegate.nDrawPath(BaseCanvas_Delegate.java:324)
	at android.graphics.drawable.VectorDrawable_Delegate$VPathRenderer_Delegate.drawPath(VectorDrawable_Delegate.java:1180)
	at android.graphics.drawable.VectorDrawable_Delegate$VPathRenderer_Delegate.drawGroupTree(VectorDrawable_Delegate.java:1101)
	at android.graphics.drawable.VectorDrawable_Delegate$VPathRenderer_Delegate.draw(VectorDrawable_Delegate.java:1109)
	at android.graphics.drawable.VectorDrawable_Delegate.nDraw(VectorDrawable_Delegate.java:157)
	at android.graphics.drawable.VectorDrawable.nDraw(VectorDrawable.java)
	at android.graphics.drawable.VectorDrawable.draw(VectorDrawable.java:338)
	at android.widget.TextView.onDraw(TextView.java:6793)
	at android.view.View.draw(View.java:19154)
	at carbon.widget.Button.drawInternal(Button.java:381)
	at carbon.widget.Button.draw(Button.java:394)
	at android.view.View.draw(View.java:19024)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4235)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4021)
	at android.view.View.draw(View.java:19157)
	at android.view.View.draw(View.java:19024)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4235)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4021)
	at android.view.View.draw(View.java:19022)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4235)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4235)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4021)
	at android.view.View.draw(View.java:19157)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:403)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:541)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:424)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:108)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:154)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:136)
	at com.android.tools.idea.rendering.RenderTask.lambda$renderInner$5(RenderTask.java:759)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Can you point out any correct way to directly use SVG on carbon's Button as drawableTop/Bottom/Left/Right? It works on drawableStart/End though. Thanks in advance.

**Comment by ZieIony** [comment]
Your stacktrace does not contain any reference to SVG drawables used by Carbon. You can set an SVG as a compound drawable using the following code:

    Button b = findViewById(R.id.button);
    Drawable v = new carbon.drawable.VectorDrawable(getResources(), R.raw.carbon_clear)
    b.setCompoundDrawables(v, null, null, null);

And the result:

![image](https://user-images.githubusercontent.com/10180628/32922546-016dbf1c-cb33-11e7-8eb8-920f402dc268.png)

**Comment by Andrei-Stakov** [comment]
Sorry for the late reply, got stuck on many IRL things.

So the vector drawable reference doesn't even showed up in stacktrace?
Weird though, beacuse I properly inserted the vector drawable reference inside the XML (on drawableTop/Bottom/Left/Right obivously).

Oh yeah, one more thing; it only happens when the theme for the layout was set to one of Carbon's. When it was set to AppCompat, it was properly rendered like usual.

[Here's the sample app](https://github.com/Andrei-Stakov/TestApp) that I modified a bit to show it. v27 with AppCompat, while v25 with Carbon's theme.

Edit: Added a sample app to showcase the issue.

**Comment by ZieIony** [comment]
In #339 I wrote that I remembered that there was another issue with RasterFormatException and there it is. And you're the autor! I forgot about it long time ago since closed issues don't show up on the issue list - I'm sorry for that.

There's no single SVG in the sample app. The vector drawables you're using are not SVGs and therefore these files are not handled by Carbon, but by Android framework. The theme thing seems interesting though. I'll check that.

**Comment by Andrei-Stakov** [comment]
And to think that I forgot about this one...

Oh yeah, sorry for the confusion; it was vector drawable, not SVG. I remember that I bring up this issue when I was half asleep working on a project.

**Comment by ZieIony** [comment]
I checked the sample with the most recent Carbon, Gradle and Android Studio. The issue seems to be gone - the layout renders correctly with Carbon's themes. It doesn't render with AppCompat themes, but this is the correct result, because Carbon's widgets rely on Carbon's themes. Recent versions even more than before.

**Comment by Andrei-Stakov** [comment]
Thanks for the fixes!
