### ISSUE TITLE
IndexOutOfBoundsException in FrameLayout 

### ISSUE THREAD

**Issue by ghost** [ZieIony/Carbon#324]
From crashlytics our users sometimes encounter this crash
```
Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
       at java.util.ArrayList.get(ArrayList.java:411)
       at carbon.widget.FrameLayout.getChildDrawingOrder(FrameLayout.java:328)
       at android.view.View.populateAccessibilityNodeInfoDrawingOrderInParent(View.java:7638)
       at android.view.View.onInitializeAccessibilityNodeInfoInternal(View.java:7597)
       at android.widget.TextView.onInitializeAccessibilityNodeInfoInternal(TextView.java:10729)
       at android.view.View.onInitializeAccessibilityNodeInfo(View.java:7213)
       at android.view.View.createAccessibilityNodeInfoInternal(View.java:7172)
       at android.view.View.createAccessibilityNodeInfo(View.java:7157)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1114)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1137)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1137)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1137)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1137)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchDescendantsOfRealNode(AccessibilityInteractionController.java:1137)
       at android.view.AccessibilityInteractionController$AccessibilityNodePrefetcher.prefetchAccessibilityNodeInfos(AccessibilityInteractionController.java:938)
       at android.view.AccessibilityInteractionController.findAccessibilityNodeInfoByAccessibilityIdUiThread(AccessibilityInteractionController.java:202)
       at android.view.AccessibilityInteractionController.-wrap1(AccessibilityInteractionController.java)
       at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1298)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6776)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
```
Please help.
Thanks

**Comment by ZieIony** [comment]
This issue was already fixed. The stacktrace doesn't point to anything in the current Carbon's code. Please update Carbon to the most recent version.

**Comment by ghost** [comment]
thanks for your help :smile:
