### ISSUE TITLE
RuntimeException setCursorColor on some devices

### ISSUE THREAD

**Issue by echr** [ZieIony/Carbon#326]
Hello, i have some issue from our users with **OPPO Smartphone**, they complaint that my apps always crash when opening the apps. when i check the crash analytics i found this error log. I think it's related with the `carbon.Widget.EditText`. any idea how to fix this issue?

i'm using the version `0.15.0.1`

        java.lang.RuntimeException: Unable to start activity 
        android.view.InflateException: Binary XML file line #0: Error inflating class carbon.widget.EditText
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2594)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2685)
        at android.app.ActivityThread.access$900(ActivityThread.java:188)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1530)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:5836)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

        Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class carbon.widget.EditText
        at android.view.LayoutInflater.createView(LayoutInflater.java:633)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.mobpulsa.mobpulsa.ui.login.LoginActivity.onCreate(LoginActivity.java:87)
        at android.app.Activity.performCreate(Activity.java:6193)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2541)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2685)
        at android.app.ActivityThread.access$900(ActivityThread.java:188)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1530)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:5836)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)
        
        Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance(Constructor.java:-2)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        

       Caused by: java.lang.RuntimeException: This feature is implemented using reflection. If you see this exception, something in your setup is not standard. Please create an issue on https://github.com/ZieIony/Carbon/issues. Please provide at least the following information: 
        - device: OPPO CPH1605, API 22
        - method: java.lang.Thread.getStackTrace(...)

        at carbon.Carbon.throwReflectionError(Carbon.java:426)
        at carbon.widget.EditText.setCursorColor(EditText.java:307)
        at carbon.widget.EditText.initEditText(EditText.java:193)
        at carbon.widget.EditText.<init>(EditText.java:111)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:-2)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
        at android.view.LayoutInflater.createView(LayoutInflater.java:607)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.mobpulsa.mobpulsa.ui.login.LoginActivity.onCreate(LoginActivity.java:87)
        at android.app.Activity.performCreate(Activity.java:6193)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2541)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2685)
        at android.app.ActivityThread.access$900(ActivityThread.java:188)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1530)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:5836)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)`

Thanks.

**Comment by ZieIony** [comment]
So, the error message doesn't tell anything (which is my fault, because I should pass the original exception to Carbon.throwReflectionError()) and I don't have access to that phone, so I'm unable to debug it.

To fix it now, you can extend `carbon.widget.EditText` and override `setCursorColor(...)` to an empty method.

If you have access to that phone, you could help me with a better fix. I would need the cause stacktrace. You could get that by setting a breakpoint on EditText:307. Without that I can't really do anything.

**Comment by echr** [comment]
Thank's for your response, i will try to fix this issue with temporary method as you suggested.
about the phone, i have no access to that phone right now, but i'll try to find that phone model and simulate it to trace the bug.

**Comment by ZieIony** [comment]
I've seen this error recently on one of the popular Samsung phones. I suppose that it may be caused by a change in the support libraries. I've changed rethrowing exceptions to logging them long time ago, but I didn't have time to investigate this issue any further yet.

**Comment by ZieIony** [comment]
I never got that Oppo phone, I didn't manage to make setCursorColor work reliably, and EditText internals change from version to version, so using reflection doesn't really work. I switched to using the approach AppCompatEditText uses, which is a special Context serving tinted resources copied from a more recent version of Android (works for handles too). Because of that setCursorColor got deprecated and to change cursor color one has to provide a theme with a cursor color set as the secondary color.
