### ISSUE TITLE
EditText render problem on Android Studio 3.1

### ISSUE THREAD

**Issue by Andrei-Stakov** [ZieIony/Carbon#339]
IDK what happened, but EditText failed to render any texts on Android Studio 3.1's preview pane. It was perfectly fine on previous version of Studio.

Here's the message:

```
java.awt.image.RasterFormatException: (x + width) is outside raster
	at sun.awt.image.IntegerInterleavedRaster.createWritableChild(IntegerInterleavedRaster.java:467)
	at sun.awt.image.IntegerInterleavedRaster.createChild(IntegerInterleavedRaster.java:514)
	at sun.java2d.pipe.GeneralCompositePipe.renderPathTile(GeneralCompositePipe.java:106)
	at sun.java2d.pipe.AAShapePipe.renderTiles(AAShapePipe.java:201)
	at sun.java2d.pipe.AAShapePipe.fillParallelogram(AAShapePipe.java:102)
	at sun.java2d.pipe.PixelToParallelogramConverter.fillRectangle(PixelToParallelogramConverter.java:322)
	at sun.java2d.pipe.PixelToParallelogramConverter.fillRect(PixelToParallelogramConverter.java:115)
	at sun.java2d.pipe.ValidatePipe.fillRect(ValidatePipe.java:76)
	at sun.java2d.SunGraphics2D.fillRect(SunGraphics2D.java:2421)
	at android.graphics.PorterDuffColorFilter_Delegate.applyFilter(PorterDuffColorFilter_Delegate.java:71)
	at com.android.layoutlib.bridge.impl.GcSnapshot.drawInLayer(GcSnapshot.java:665)
	at com.android.layoutlib.bridge.impl.GcSnapshot.draw(GcSnapshot.java:585)
	at android.graphics.BaseCanvas_Delegate.draw(BaseCanvas_Delegate.java:558)
	at android.graphics.BaseCanvas_Delegate.nDrawRect(BaseCanvas_Delegate.java:210)
	at android.graphics.BaseCanvas.nDrawRect(BaseCanvas.java)
	at android.graphics.BaseCanvas.drawRect(BaseCanvas.java:340)
	at android.graphics.Canvas.drawRect(Canvas.java:1755)
	at android.graphics.BaseCanvas.drawRect(BaseCanvas.java:345)
	at android.graphics.Canvas.drawRect(Canvas.java:1741)
	at android.graphics.drawable.ColorDrawable.draw(ColorDrawable.java:112)
	at android.view.View.drawBackground(View.java:19399)
	at android.view.View.draw_Original(View.java:19183)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:19162)
	at carbon.widget.EditText.drawInternal(EditText.java:567)
	at carbon.widget.EditText.draw(EditText.java:736)
	at android.view.View.draw_Original(View.java:19062)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:18834)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4236)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at carbon.widget.LinearLayout.drawChild(LinearLayout.java:321)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at carbon.widget.LinearLayout.dispatchDrawInternal(LinearLayout.java:282)
	at carbon.widget.LinearLayout.dispatchDraw(LinearLayout.java:274)
	at android.view.View.draw_Original(View.java:19195)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:19162)
	at carbon.widget.LinearLayout.drawInternal(LinearLayout.java:391)
	at carbon.widget.LinearLayout.draw(LinearLayout.java:407)
	at android.view.View.draw_Original(View.java:19062)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:18834)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4236)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at carbon.widget.ConstraintLayout.drawChild(ConstraintLayout.java:304)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at carbon.widget.ConstraintLayout.dispatchDrawInternal(ConstraintLayout.java:266)
	at carbon.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:258)
	at android.view.View.draw_Original(View.java:19060)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:18834)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4236)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.draw_Original(View.java:19060)
	at android.view.View_Delegate.draw(View_Delegate.java:68)
	at android.view.View.draw(View.java:18834)
	at android.view.ViewGroup.drawChild_Original(ViewGroup.java:4236)
	at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:63)
	at android.view.ViewGroup.drawChild(ViewGroup.java:4236)
	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4022)
	at android.view.View.draw_Original(View.java:19195)
	at android.view.View_Delegate.draw(View_Delegate.java:56)
	at android.view.View.draw(View.java:19162)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:403)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.renderAndBuildResult(RenderSessionImpl.java:541)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.render(RenderSessionImpl.java:424)
	at com.android.layoutlib.bridge.BridgeRenderSession.render(BridgeRenderSession.java:108)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:154)
	at com.android.ide.common.rendering.api.RenderSession.render(RenderSession.java:136)
	at com.android.tools.idea.rendering.RenderTask.lambda$renderInner$5(RenderTask.java:757)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by ZieIony** [comment]
I've seen this problem before with other widgets. If I remember correctly, it was related to 0px Canvas used for drawing side drawables. I'll investigate that.

**Comment by ZieIony** [comment]
I just updated everything and I'm unable to reproduce your issue. Could you provide me with a minimal working example of your issue?

**Comment by Andrei-Stakov** [comment]
Here's the quick sample with the same gradle setup:

https://github.com/Andrei-Stakov/MyApplication3

It was fine on Android Studio 3.0.1 (using SDK 26 as target, gradle 3.0.1, and 4.1 wrapper), but the render for carbon.EditText is breaking in the latest stable (with updated SDK to 27, gradle 3.1.0, and 4.4 wrapper).

**Comment by ZieIony** [comment]
Thank you very much. The updated version is in the repository. I updated edit mode drawing for most of Carbon's widgets. I try to make a release soon.

**Comment by ZieIony** [comment]
I checked your sample with most recent version of Carbon, Gradle and Android Studio and the problem seems to be gone. There's another issue with font loading, but that's another story.

**Comment by Andrei-Stakov** [comment]
Thanks for the fixes!
