### ISSUE TITLE
NullPointerException in setBackground()

### ISSUE THREAD

**Issue by dmitriigriazin** [ZieIony/Carbon#35]
Whenever I use `android:background` attr, I get expection in the view's method. Tried only with CardView/LinearLayout.

App theme is `carbon_Theme.AppCompat.Light`

```
        <carbon.widget.CardView
        android:layout_height="wrap_content"
        android:layout_width="match_parent"
        android:layout_margin="8dp"
        android:clickable="true"
        android:descendantFocusability="blocksDescendants"
        app:carbon_rippleColor="#42ff0000"
        app:carbon_elevation="2dp"
        app:carbon_rippleStyle="over"
        app:carbon_touchMargin="6dp"
        android:background="@drawable/pink_rect">
```

StackTrace:

```
        Caused by: java.lang.NullPointerException
        at carbon.widget.CardView.setBackground(CardView.java:98)
        at android.view.View.<init>(View.java:4025)
        at android.view.ViewGroup.<init>(ViewGroup.java:480)
        at android.widget.LinearLayout.<init>(LinearLayout.java:176)
        at android.widget.LinearLayout.<init>(LinearLayout.java:172)
        at carbon.widget.CardView.<init>(CardView.java:24)
        at java.lang.reflect.Constructor.constructNative(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at android.view.LayoutInflater.createView(LayoutInflater.java:600)
```

An exception is thrown either a drawable shape or just a color is set in XML

**Comment by ZieIony** [comment]
The reason is that CardView tries to set a background to a container which is not ready yet. If you wish to set a background for a card, you should place a view with a background inside of the card. You can also replace CardView with a layout.

I'm marking this as a bug. Cards are in phase of experiments for now. In the end I think that the CardView class will be a FrameLayout with a custom style. CardView is that simple.

**Comment by ZieIony** [comment]
no answer for 7 days - I'm closing the issue

**Comment by ZieIony** [comment]
CardView should be much better now (0.7.0).
