### ISSUE TITLE
android.view.InflateException: Binary XML file line

### ISSUE THREAD

**Issue by jomarierafa** [ZieIony/Carbon#379]
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.equipmentmonitoring, PID: 6297
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.equipmentmonitoring/com.example.equipmentmonitoring.LoginActivity}: android.view.InflateException: Binary XML file line #73: Binary XML file line #73: Error inflating class carbon.widget.Button
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: android.view.InflateException: Binary XML file line #73: Binary XML file line #73: Error inflating class carbon.widget.Button
     Caused by: android.view.InflateException: Binary XML file line #73: Error inflating class carbon.widget.Button
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.example.equipmentmonitoring.LoginActivity.onCreate(LoginActivity.kt:10)
        at android.app.Activity.performCreate(Activity.java:7183)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 22: TypedValue{t=0x2/d=0x7f0300c2 a=2}
        at android.content.res.TypedArray.getColor(TypedArray.java:469)
        at carbon.Carbon.getDefaultColorStateList(Carbon.java:85)
        at carbon.Carbon.initRippleDrawable(Carbon.java:160)
        at carbon.widget.Button.initButton(Button.java:186)
        at carbon.widget.Button.<init>(Button.java:97)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
        at com.example.equipmentmonitoring.LoginActivity.onCreate(LoginActivity.kt:10) 
        at android.app.Activity.performCreate(Activity.java:7183) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6944) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374) 
```

**Comment by ZieIony** [comment]
Could you please share more details about your issue? What version of Android and Carbon are you using. Please also check if you integrated Carbon correctly (for example, are you using Carbon theme for your activities).

**Comment by jomarierafa** [comment]
Im using 
Carbon 0.15.2
Android Studio 3.3

carbon.widget.TextView is working, but carbon.widget.Button is not working

**Comment by ZieIony** [comment]
Well, this is strange. I'll check this value (0x7f0300c2), maybe it will shed some light on this issue. If you could prepare a minimal example project showing your issue for me or share your project with me, that would be very helpful.

**Comment by jomarierafa** [comment]
> Could you please share more details about your issue? What version of Android and Carbon are you using. Please also check if you integrated Carbon correctly (for example, are you using Carbon theme for your activities).

its working now i forgot to integrate carbon theme "carbon_Theme.Light.NoActionBar"
but its weird that textview is working while button is not working without integrating the carbon theme btw thanks you for the response.

**Comment by ZieIony** [comment]
Some of widgets use nonstandard attributes and may require the theme while other work fine without it, so that may be the case. I'm glad that it works for you now.
