### ISSUE TITLE
ShadowRenderer.drawCornerShadow - IllegalArgumentException: radius must be > 0

### ISSUE THREAD

**Issue by ZieIony** [ZieIony/Carbon#388]
For the moment, it's my failure that I removed the Theme that in style.xml, so when I added it back, Carbon works well, but below exception occured : 

    java.lang.IllegalArgumentException: radius must be > 0
        at android.graphics.RadialGradient.<init>(RadialGradient.java:59)
        at carbon.shadow.ShadowRenderer.drawCornerShadow(ShadowRenderer.java:158)
        at carbon.shadow.ShapePath$ArcShadowOperation.draw(ShapePath.java:289)
        at carbon.shadow.ShapePath$1.draw(ShapePath.java:179)
        at carbon.shadow.ShapePath$ShadowCompatOperation.draw(ShapePath.java:229)
        at carbon.shadow.MaterialShapeDrawable.drawCompatShadow(MaterialShapeDrawable.java:383)
        at carbon.shadow.MaterialShapeDrawable.draw(MaterialShapeDrawable.java:344)
        at carbon.widget.ImageView.drawShadow(ImageView.java:619)
        at carbon.widget.ConstraintLayout.drawChild(ConstraintLayout.java:313)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2023)
        at carbon.widget.ConstraintLayout.dispatchDrawInternal(ConstraintLayout.java:290)
        at carbon.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:282)
        at android.view.View.draw(View.java:17308)
        at carbon.widget.ConstraintLayout.drawInternal(ConstraintLayout.java:420)
        at carbon.widget.ConstraintLayout.draw(ConstraintLayout.java:482)
        at android.view.View.updateDisplayListIfDirty(View.java:16282)
        at android.view.View.draw(View.java:17066)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.updateDisplayListIfDirty(View.java:16277)
        at android.view.View.draw(View.java:17066)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.updateDisplayListIfDirty(View.java:16277)
        at android.view.View.draw(View.java:17066)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3727)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3513)
        at android.view.View.draw(View.java:17308)
        at com.android.internal.policy.DecorView.draw(DecorView.java:786)
        at android.view.View.updateDisplayListIfDirty(View.java:16282)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:661)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:667)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:775)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:2829)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2637)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2239)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1270)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6464)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:888)
        at android.view.Choreographer.doCallbacks(Choreographer.java:700)
        at android.view.Choreographer.doFrame(Choreographer.java:635)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:874)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6405)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1003)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:893)

_Originally posted by @codingCavalier in https://github.com/ZieIony/Carbon/issues/387#issuecomment-522464163_

**Comment by ZieIony** [comment]
Is there has any problem?

PathArcOperation pathArcOperation = new PathArcOperation(endX, endY, endX, endY);
pathArcOperation.startAngle = currentShadowAngle;
pathArcOperation.sweepAngle = shadowSweep;
shadowCompatOperations.add(new ArcShadowOperation(pathArcOperation));
currentShadowAngle = nextShadowAngle;

_Originally posted by @codingCavalier in https://github.com/ZieIony/Carbon/issues/387#issuecomment-522464163_

**Comment by ZieIony** [comment]
Could you please provide more information about your issue? This error is most likely related to the size of a view in your layout or its shadow.

As a side note - `MaterialShapeDrawable` and other shadow-drawing code is borrowed from Material Components, so there may already be an answer for this issue on SO or Google's issue tracker.

**Comment by codingCavalier** [comment]
I used carbon.widget.ImageView and carbon.widget.ConstraintLayout wraped the ImageView as it's parent (in order to draw the shadow).

But when I moved other views that wraped in the same ConstraintLayout, then crashed, and below exception occurred. It sames occurred because of drawing the shadow of ImageView.

java.lang.IllegalArgumentException: radius must be > 0

**Comment by codingCavalier** [comment]
Now, the new problem is I am not used carbon.widget.ImageView and I just used carbon.widget.ConstraintLayout (wrap an android.widget.ImageView) , then this exception also occurred...

**Comment by ZieIony** [comment]
I tried to use ConstraintLayout with a bunch of different options and I'm unable to reproduce your issue. ConstraintLayout uses the same drawing code as all other layouts and views and the shadow drawing code is provided by Google.

If you wish me to help you, please provide minimal working example of the faulty code/xml/configuration. Ideally please share the project on GitHub - the issue can be not in the layout, but somewhere else.

**Comment by codingCavalier** [comment]
Could you contact me by email of zhuang_du@163.com?

**Comment by ZieIony** [comment]
I don't usually do that. All issues related to Carbon should be discussed here, so others can contribute and benefit from these discussions.

**Comment by codingCavalier** [comment]
It sames that the bounds width will be zero, so the exception occurred

![TIM截图20190822113401](https://user-images.githubusercontent.com/26496772/63573028-df256380-c5b6-11e9-8a02-f217c2d0fb7f.png)
![TIM截图20190822113313](https://user-images.githubusercontent.com/26496772/63573029-df256380-c5b6-11e9-952d-5f8fa66887d6.png)
![TIM图片20190822113159](https://user-images.githubusercontent.com/26496772/63573030-df256380-c5b6-11e9-96f2-1a9b70879d49.png)

**Comment by codingCavalier** [comment]
I catched the crash Instantaneous, it shows that when the elevation was less than 0.5, it be round to 0, and so ... it will crash immediately

I guess the causes is performing animation in translationZ, and it will draw shadow from small to large, when it gradual changes from 0 to target size.

![TIM截图20190823154647](https://user-images.githubusercontent.com/26496772/63575678-43e3bc80-c5bd-11e9-8865-f6a354cecd29.png)

**Comment by codingCavalier** [comment]
Your sample code used carbon.widget.Button, but I used carbon.widget.ImageView as button

Butttt, why, when I used carbon.widget.Button and set width/2 = height/2 = carbon_cornerRadius, my code crashhhhhed, 5555555

So, I used 21.999dp as carbon_cornerRadius when the view size is 44dp ...
