### ISSUE TITLE
java.lang.VerifyError when using carbon.widget.LinearLayout

### ISSUE THREAD

**Issue by libf-de** [ZieIony/Carbon#40]
when i open my app it's crashing with the following error:

```
03-06 17:35:28.452  32415-32415/de.xorg.gsapp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: de.xorg.gsapp, PID: 32415
    java.lang.VerifyError: carbon/shadow/ShadowGenerator
            at carbon.widget.RelativeLayout.drawChild(RelativeLayout.java:106)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2962)
            at carbon.widget.RelativeLayout.dispatchDraw(RelativeLayout.java:89)
            at android.view.View.draw(View.java:14389)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3118)
            at carbon.widget.LinearLayout.drawChild(LinearLayout.java:146)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2962)
            at carbon.widget.LinearLayout.dispatchDraw(LinearLayout.java:84)
            at android.view.View.draw(View.java:14389)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3118)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2955)
            at android.view.View.draw(View.java:14389)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3118)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2955)
            at android.view.View.draw(View.java:14389)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3118)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2955)
            at android.view.View.draw(View.java:14509)
            at android.widget.FrameLayout.draw(FrameLayout.java:472)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2451)
            at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2546)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2459)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2301)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1931)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1047)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5896)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
            at android.view.Choreographer.doCallbacks(Choreographer.java:574)
            at android.view.Choreographer.doFrame(Choreographer.java:544)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5103)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:790)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:606)
            at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ZieIony** [comment]
Usually the VerifyError is a result of using different libraries in compile time and runtime. Did you get that error before? Did you try to clean and rebuild your project? Are you doing anything unusual in your configuration files?

**Comment by libf-de** [comment]
nevermind, i forgot to insert renderscript stuff in android build config

**Comment by zzz40500** [comment]
thanks for @XorgMC  ,I solved the same problem
