### ISSUE TITLE
PagerTabStrip crashes when empty

### ISSUE THREAD

**Issue by ZieIony** [ZieIony/Carbon#42]
java.lang.NullPointerException   at carbon.widget.PagerTabStrip.draw(PagerTabStrip.java:165)   at android.view.View.draw(View.java:15022)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3404)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:53)   at android.view.ViewGroup.drawChild(ViewGroup.java:3404)   at carbon.widget.LinearLayout.drawChild(LinearLayout.java:93)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)   at carbon.widget.LinearLayout.dispatchDraw(LinearLayout.java:84)   at android.view.View.draw(View.java:15017)   at android.view.ViewGroup.drawChild_Original(ViewGroup.java:3404)   at android.view.ViewGroup_Delegate.drawChild(ViewGroup_Delegate.java:53)   at android.view.ViewGroup.drawChild(ViewGroup.java:3404)   at carbon.widget.LinearLayout.drawChild(LinearLayout.java:93)   at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)   at carbon.widget.LinearLayout.dispatchDraw(LinearLayout.java:84)   at android.view.View.draw(View.java:15017)

**Comment by ZieIony** [comment]
fixed
