### ISSUE TITLE
Using Carbon's FrameLayout as a container for fragments results in an ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by DSteve595** [ZieIony/Carbon#62]
Using `0.7.2`.

I have (in a DrawerLayout, though I don't think it matters) a `carbon.widget.FrameLayout` that I'm using as a container for `FragmentTransaction`s. I do this in my activity:

```
getSupportFragmentManager().beginTransaction()
                        .disallowAddToBackStack()
                        .replace(R.id.content, fragment)
                        .commit();
```

Here's my layout:

```
<carbon.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/*removed*"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clipChildren="false"
    android:fitsSystemWindows="true">

    <carbon.widget.FrameLayout
        android:id="@+id/content"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content" />

    <carbon.widget.ScrimInsetsLayout
        android:id="@+id/*removed*"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        android:background="@android:color/white"
        android:fitsSystemWindows="true"
        app:carbon_elevation="4dp"
        app:carbon_insetForeground="#4000">

        <fragment
            android:id="@+id/fragment_drawer"
            android:name="*removed*.DrawerFragment"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            tools:layout="@layout/wallet_drawer" />
    </carbon.widget.ScrimInsetsLayout>
</carbon.widget.DrawerLayout>
```

The first fragment transaction works fine. However, a subsequent one gives the following crash:

```
    java.lang.ArrayIndexOutOfBoundsException: length=12; index=-1
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3195)
            at carbon.widget.FrameLayout.dispatchDraw(FrameLayout.java:100)
            at android.view.View.draw(View.java:15117)
            at android.widget.FrameLayout.draw(FrameLayout.java:592)
            at carbon.widget.FrameLayout.draw(FrameLayout.java:236)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1086)
            at carbon.widget.DrawerLayout.drawChild(DrawerLayout.java:168)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at carbon.widget.DrawerLayout.dispatchDraw(DrawerLayout.java:99)
            at android.view.View.draw(View.java:15117)
            at carbon.widget.DrawerLayout.draw(DrawerLayout.java:235)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.updateDisplayListIfDirty(View.java:14043)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.View.draw(View.java:14838)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3404)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
            at android.view.View.draw(View.java:15117)
            at android.widget.FrameLayout.draw(FrameLayout.java:592)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2595)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)
            at android.view.View.getDisplayList(View.java:14071)
            at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:266)
            at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:272)
            at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:311)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2492)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2337)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1968)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1054)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5779)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:550)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

Simply changing the `carbon.widget.FrameLayout` to a regular Android `FrameLayout`, with no other changes, fixes the issue.

My guess is it's something to do with the z-ordering Carbon does, but I'm not sure.

This isn't catastrophic for my case as using a regular FrameLayout is fine, but it could impede the use of shadows in some other cases.

**Comment by ZieIony** [comment]
Your guess might be pretty good as it looks like a default index for an item not found in a collection. Could you please provide me with version of the Android you're running the code on? If it's modified (Samsung's TouchWiz, Cyanogen, etc.), please add the name of the mod as well.

If you wish, you can check the potential bugfix by yourself. To do that, remove rows 93 and 97 from carbon.widget.FrameLayout.

**Comment by DSteve595** [comment]
Stock AOSP, Android 5.0.1 emulator.

**Comment by ZieIony** [comment]
Changed z-order sorting - it's now triggered every draw. There's no release yet (regression tests)

**Comment by ZieIony** [comment]
I'm sorry that it took so long, but I was superbusy recently. Check out the ScrimInsetsLayout sample - it reproduces your case and, with recent updates, works flawlessly for me.

Also, ScrimInsetsLayout is now depreciated. You can achieve the same result by using any of the Carbon's layouts. Just add carbon_insetTop="0dp".

**Comment by DSteve595** [comment]
No need to apologize, the work is greatly appreciated.
Will adding `insetTop="0dp"' actually replace the ScrimInsetsLayout's job? From what I remember, ScrimInsetsLayout used the insets from the status bar to draw a color over the inset area (usually transparent gray). Will this do the same? And if so, how is the color chosen?

**Comment by ZieIony** [comment]
Oh, right. Two cases:
1. To color the status bar:

```
    <carbon.widget.LinearLayout
        app:carbon_insetColor="#ffffffff"
        android:fitsSystemWindows="true">
```
1. To override the top inset:

```
    <carbon.widget.LinearLayout
        app:carbon_insetTop="5dp"
        android:fitsSystemWindows="true">
```

**Comment by DSteve595** [comment]
Will try soon, thanks so much!

**Comment by DSteve595** [comment]
Looks good! I did, however, use the `setOnInsetsCallback()` method of ScrimInsetsLayout, which seems like it could be implemented by the InsetView interface. Would that be possible?

**Comment by ZieIony** [comment]
I thought it was useless, that's why it's not there. But why not, see #70

**Comment by AlexMomotov** [comment]
The error is still there in 0.11.0 version. :(

**Comment by ayalma** [comment]
Can you add java and xml Code here
