### ISSUE TITLE
Hardware Acceleration Crash

### ISSUE THREAD

**Issue by Gericom** [ZieIony/Carbon#65]
If I have hardware acceleration enabled on my ASUS TF101 (Android 4.0.3), it crashes when trying to clip the content of a view with rounded corners. With hardware acceleration disabled it works. Also, on my Phone (Samsung Galaxy Fame with Android 4.1) it does not crash, but the rounded corners do not work.

04-08 18:25:21.170  24248-24248/com.nouwt.florian.apps.magica E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.UnsupportedOperationException
            at android.view.GLES20Canvas.clipPath(GLES20Canvas.java:408)
            at carbon.widget.LinearLayout.draw(LinearLayout.java:229)
            at android.view.View.getDisplayList(View.java:10422)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
            at com.nouwt.florian.apps.magica.ui.DayView2.drawChild(DayView2.java:262)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
            at com.nouwt.florian.apps.magica.ui.DayView2.dispatchDraw(DayView2.java:188)
            at android.view.View.getDisplayList(View.java:10420)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
            at android.view.View.draw(View.java:10986)
            at android.widget.FrameLayout.draw(FrameLayout.java:450)
            at android.widget.ScrollView.draw(ScrollView.java:1524)
            at carbon.widget.ScrollView.draw(ScrollView.java:68)
            at android.view.View.getDisplayList(View.java:10422)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
            at carbon.widget.LinearLayout.drawChild(LinearLayout.java:168)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2496)
            at carbon.widget.LinearLayout.dispatchDraw(LinearLayout.java:99)
            at android.view.View.draw(View.java:10986)
            at carbon.widget.LinearLayout.draw(LinearLayout.java:235)
            at android.view.View.getDisplayList(View.java:10422)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
            at carbon.widget.FrameLayout.drawChild(FrameLayout.java:169)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2496)
            at carbon.widget.FrameLayout.dispatchDraw(FrameLayout.java:100)
            at android.view.View.draw(View.java:10986)
            at android.widget.FrameLayout.draw(FrameLayout.java:450)
            at carbon.widget.FrameLayout.draw(FrameLayout.java:236)
            at android.view.View.getDisplayList(View.java:10422)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
            at carbon.widget.LinearLayout.drawChild(LinearLayout.java:168)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2496)
            at carbon.widget.LinearLayout.dispatchDraw(LinearLayout.java:99)
            at android.view.View.draw(View.java:10986)
            at carbon.widget.LinearLayout.draw(LinearLayout.java:235)
            at android.view.View.getDisplayList(View.java:10422)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
            at android.view.View.draw(View.java:10986)
            at android.support.v4.view.ViewPager.draw(ViewPager.java:2176)
            at android.view.View.getDisplayList(View.java:10422)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
            at carbon.widget.LinearLayout.drawChild(LinearLayout.java:168)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2496)
            at carbon.widget.LinearLayout.dispatchDraw(LinearLayout.java:99)
            at android.view.View.draw(View.java:10986)
            at carbon.widget.LinearLayout.draw(LinearLayout.java:235)
            at android.view.View.getDisplayList(View.java:10422)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2489)
            at android.view.View.getDisplayList(View.java:10420)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
            at carbon.widget.LinearLayout.drawChild(LinearLayout.java:168)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2496)
            at carbon.widget.LinearLayout.dispatchDraw(LinearLayout.java:99)
            at android.view.View.draw(View.java:10986)
            at carbon.widget.LinearLayout.draw(LinearLayout.java:235)
            at android.view.View.getDisplayList(View.java:10422)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
            at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1086)
            at carbon.widget.DrawerLayout.drawChild(DrawerLayout.java:168)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2496)
            at carbon.widget.DrawerLayout.dispatchDraw(DrawerLayout.java:99)
            at android.view.View.draw(View.java:10986)
            at carbon.widget.DrawerLayout.draw(DrawerLayout.java:235)
            at android.view.View.getDisplayList(View.java:10422)
            at android.view.ViewGroup.drawChild(ViewGroup.java:2850)
            at android.view.ViewGroup.dispa

**Comment by ZieIony** [comment]
I must admit I totally forgot about unsupported clipping. Android doesn't support hardware clipping on versions 11 to 17. Texture clipping (like buttons) is not an option for layouts due to animation issues.

For now you have to either remove rounded corners or disable hardware acceleration for these layouts. I'm marking this as a bug. Thanks for reporting the issue!

**Comment by Gericom** [comment]
If it would be possible to disable hardware acceleration just for the elements that have rounded corners, that would probably be a nice solution. But be careful, because text is rendered different if no hardware acceleration is used.

**Comment by ZieIony** [comment]
Software layers are ignored on some devices, so turning the hardware acceleration off for clipped layouts is a bad idea. For now rounded corners are not really usable on ICS devices.

My goal is to implement texture clipping correctly. It has the best quality and works on all devices. It's pretty slow though.

**Comment by Gericom** [comment]
Maybe you can add an option to disable clipping. For example in my case I don't need clipping. Only the rounded corners.

**Comment by ZieIony** [comment]
If you need only rounded corners, you can set a rounded rect as a background.

I need some time to research and implement possible solutions. Maybe this weekend :)

**Comment by ZieIony** [comment]
I found nice solution for your case. It's in 0.7.3 release, so you can try it out. It works well on Galaxy S III mini with Android 4.1

**Comment by Gericom** [comment]
Thanks! I will give it a try.
