### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by siavashkavousi** [ZieIony/Carbon#66]
Hi
when I add your library to my project, build is successful after that on run, I've faced with this problem

Error Code:
    2
Output:
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Lcom/nineoldandroids/animation/Animator$AnimatorListener;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)

**Comment by ZieIony** [comment]
Carbon uses NineOldAndroids to support animations on older devices. Carbon specifies that library as a dependency, so it should work nicely. You're using this library in one of the other modules. Perhaps you have NineOldAndroid included as a jar somewhere.

Try to look for NineOldAndroids in your project and remove the duplicate.
