### ISSUE TITLE
ShadowGenerator crashes with 0dp views

### ISSUE THREAD

**Issue by ZieIony** [ZieIony/Carbon#73]
```
java.lang.IllegalArgumentException: width and height must be > 0
            at android.graphics.Bitmap.createBitmap(Bitmap.java:901)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:880)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:847)
            at carbon.shadow.ShadowGenerator.generateShadow(ShadowGenerator.java:115)
            at carbon.widget.LinearLayout.drawChild(LinearLayout.java:134)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3142)
            at carbon.widget.LinearLayout.dispatchDraw(LinearLayout.java:103)
```

**Comment by ZieIony** [comment]
fixed in 0.7.4
