### ISSUE TITLE
Error after adding ImageActionButton to carbon.widget.FrameLayout frome code.

### ISSUE THREAD

**Issue by dawidhyzy** [ZieIony/Carbon#99]
java.lang.VerifyError: carbon/shadow/ShadowGenerator
            at carbon.widget.ImageView.getShadow(ImageView.java:271)
            at carbon.widget.FrameLayout.drawChild(FrameLayout.java:127)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2947)
            at carbon.widget.FrameLayout.dispatchDraw(FrameLayout.java:100)
            at android.view.View.draw(View.java:14475)
            at android.widget.FrameLayout.draw(FrameLayout.java:472)
            at carbon.widget.FrameLayout.draw(FrameLayout.java:257)
            at android.view.View.getDisplayList(View.java:13369)
            at android.view.View.getDisplayList(View.java:13411)
            at android.view.View.draw(View.java:14189)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.getDisplayList(View.java:13364)
            at android.view.View.getDisplayList(View.java:13411)
            at android.view.View.draw(View.java:14189)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.getDisplayList(View.java:13364)
            at android.view.View.getDisplayList(View.java:13411)
            at android.view.View.draw(View.java:14189)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.getDisplayList(View.java:13364)
            at android.view.View.getDisplayList(View.java:13411)
            at android.view.View.draw(View.java:14189)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.support.v4.widget.DrawerLayout.drawChild(DrawerLayout.java:1089)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.getDisplayList(View.java:13364)
            at android.view.View.getDisplayList(View.java:13411)
            at android.view.View.draw(View.java:14189)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.getDisplayList(View.java:13364)
            at android.view.View.getDisplayList(View.java:13411)
            at android.view.View.draw(View.java:14189)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.draw(View.java:14475)
            at android.widget.FrameLayout.draw(FrameLayout.java:472)
            at android.view.View.getDisplayList(View.java:13369)
            at android.view.View.getDisplayList(View.java:13411)
            at android.view.View.draw(View.java:14189)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.getDisplayList(View.java:13364)
            at android.view.View.getDisplayList(View.java:13411)
            at android.view.View.draw(View.java:14189)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.getDisplayList(View.java:13364)
            at android.view.View.getDisplayList(View.java:13411)
            at android.view.View.draw(View.java:14189)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.getDisplayList(View.java:13364)
            at android.view.View.getDisplayList(View.java:13411)
            at android.view.View.draw(View.java:14189)
            at android.view.ViewGroup.drawChild(ViewGroup.java:3103)
            at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2940)
            at android.view.View.draw(View.java:14475)
            at android.widget.FrameLayout.draw(FrameLayout.java:472)
            at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2587)
            at android.view.View.getDisplayList(View.java:13369)
            at android.view.View.getDisplayList(View.java:13411)
            at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java:1570)
            at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1449)
            at android.view.ViewRootImpl.draw(ViewRootImpl.java:2381)
            at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2253)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl

**Comment by ZieIony** [comment]
This doesn't look like a problem with Carbon. I would look for an other reason: http://stackoverflow.com/questions/100107/reasons-of-getting-a-java-lang-verifyerror

**Comment by ZieIony** [comment]
No answer, doesn't look like a problem with Carbon, closing.

**Comment by ZieIony** [comment]
This issue was solved in #40
